### PR TITLE
Adding grocery static template

### PR DESCRIPTION
**Pull request by AsmaIbrahimButt**
# Description
I fixed this issue #490
I made a static grocery template page using HTML,CSS and javascript.

## Type of change

Add Project

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
page1
page2
page3
xc
fo

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Link the issue in PR description

**Comment by arpit456jain** [comment]
@AsmaIbrahimButt

**Comment by VidhiBhatt01** [comment]
Reopen this PR when ready

**Comment by AsmaIbrahimButt** [comment]
Hi @astha2412 Kindly review a pull request.Thanks

**Comment by arpit456jain** [comment]
@AsmaIbrahimButt make it responsive

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Reopen this when ready

**Comment by VidhiBhatt01** [comment]
Reopen this when ready

**Pull request closed without merging**
