### PR TITLE
Added Adobe Photo Shop Website Clone

### PR DESCRIPTION
**Pull request by eswarbhageerath**
This is the PR of the issue Adobe Photoshop Website Clone #673...please review it sir

### CODE REVIEW

**Comment by arpit456jain** [comment]
image

navbar is missing 
size of website is very large optimise it

**Comment by arpit456jain** [comment]
https://deploy-preview-680--cool-front-end-templates.netlify.app/adobe%20photoshop%20clone%20website%20clone/

**Comment by arpit456jain** [comment]
@eswarbhageerath how did u make it ?

**Comment by eswarbhageerath** [comment]
@arpit456jain  Sir, navbar is working in my local system but, I can not figure out the issue why it was missing there, I made this project as a team project for a Technical Competition in a team

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
I also cannot see the navbar. If it's working on your device, attach some SS @eswarbhageerath . Also, we cannot accept such a large PR. Reduce number of files changes to less than 50. Remove all extra features. We just want basic functionality

**Comment by eswarbhageerath** [comment]
image



@VidhiBhatt01  This is the project which I ran in my Local system, Screenshot has the NavBar

**Comment by eswarbhageerath** [comment]
@VidhiBhatt01 Please review my PR

**Review by VidhiBhatt01 — COMMENTED** [review]
I can't help unless you reduce the number of files changed

**Comment by eswarbhageerath** [comment]
@VidhiBhatt01 Reduced the files, maintained only the basic functionality

**Pull request merged**
