### PR TITLE
mobile template

### PR DESCRIPTION
**Pull request by Yashashviarora**
This issue is opened by me in this i make a mobile template

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Link the issue in PR description

**Review by DEEPIKA-SUK — CHANGES_REQUESTED** [review]
@Yashashviarora make it responsive and change the color of "click here", it is not visible.
Screenshot 2022-05-23 185543

**Review by Yashashviarora — COMMENTED** [review]
I made  a website from non-responsive to responsive

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
@DEEPIKA-SUK don't review until and unless basic requirements are met!! @Yashashviarora link the issue for this PR in the PR description using a #

**Comment by Yashashviarora** [comment]
@VidhiBhatt01  Can i make again pr by deleting this pr  ?

**Comment by VidhiBhatt01** [comment]
Sure

**Comment by Yashashviarora** [comment]
ohhk thanks

**Pull request closed without merging**
