### PR TITLE
Adding Zomato Clone

### PR DESCRIPTION
**Pull request by ProMinato500**
## Languages:

- HTML
- CSS

## **Project Description**

- Add Zomato Website Clone

### CODE REVIEW

**Comment by arpit456jain** [comment]
@ProMinato500

**Comment by ProMinato500** [comment]
> @ProMinato500 u made this from ur own?

Yes Sir

**Comment by arpit456jain** [comment]
> > @ProMinato500 u made this from ur own?
> 
> Yes Sir

@ProMinato500 link the issue or clode it

**Comment by ProMinato500** [comment]
Updated issue. Sorry for the inconvinience.

**Review by VidhiBhatt01 — COMMENTED** [review]
https://codesandbox.io/s/fkit0

**Pull request merged**
