### PR TITLE
Added Interactive-Resume-Gaming-UI Template

### PR DESCRIPTION
**Pull request by itsmohitnamdeo**
This is one of best interactive template . It is just like playing a game.

## Type of change

- [ ] Added Interactive-Resume-Gaming-UI Template 

# Checklist:
- [ ] I have taken help from some online resourses 
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

ir1
ir2

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Link the issue using # in the PR description

**Comment by VidhiBhatt01** [comment]
Also, add a short video if possible

**Comment by itsmohitnamdeo** [comment]
> Also, add a short video if possible
@VidhiBhatt01 
Short video of the Interactive-Resume-Gaming-UI Template
https://user-images.githubusercontent.com/85800451/161194785-8e811bef-a9b3-4c45-a0c7-b2a02495b50b.mp4

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
I am unable to see the video.


@arpit456jain, he raised the PR before the issue was assigned, shall I ask him to make a new PR? Also, this is a very hefty PR what are your views on this? I think it would be more suitable in JS repo

**Comment by arpit456jain** [comment]
> I am unable to see the video.
> 
> @arpit456jain, he raised the PR before the issue was assigned, shall I ask him to make a new PR? Also, this is a very hefty PR what are your views on this? I think it would be more suitable in JS repo

Yeah i also think it would be great i js projects plus
@itsmohitnamdeo the size of project is very large we can't accept this much size
If you can reduce it then create a issue on js projects and wait for assigning issue to you

**Pull request closed without merging**
