### PR TITLE
Microsoft Clone Added

### PR DESCRIPTION
**Pull request by 19arnab190201**
I have uploaded a 98% accurate clone of Microsoft's main landing page

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # 272

## Type of change
Added a net clone of Microsoft

# Explain the Testing instructions

**Test Configuration**:

- Operating system: Win 11
- Version:
- Text-editors used: VS Code

# Checklist:

- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Hello, world!

### CODE REVIEW

**Comment by VidhiBhatt01** [comment]
@19arnab190201 Did you make this on your own?

**Comment by 19arnab190201** [comment]
> @19arnab190201 Did you make this on your own?

Yes, obviously...

**Comment by VidhiBhatt01** [comment]
I meant like did you refer to any tutorial or made it completely on your own? Because this is so good and accurate!!

**Comment by 19arnab190201** [comment]
> I meant like did you refer to any tutorial or made it completely on your own? Because this is so good and accurate!!

Thanks , no I did it completely by myself all thanks to bootstrap for responsiveness and creating proper  layout

**Comment by VidhiBhatt01** [comment]
> > I meant like did you refer to any tutorial or made it completely on your own? Because this is so good and accurate!!
> 
> Thanks , no I did it completely by myself all thanks to bootstrap for responsiveness and creating proper layout

That's awesome. Keep up the good work!! 👍

**Comment by 19arnab190201** [comment]
> 

Thanks a lot for your feedback 😄

**Comment by arpit456jain** [comment]
#272

**Review by VidhiBhatt01 — COMMENTED** [review]
Approved

**Pull request merged**
