### PR TITLE
#448 - Fixed structure of all projects

### PR DESCRIPTION
**Pull request by TG922**
# Description

- [x] Added all images into the img folder and also synced the path of the images in the file

**List is here:**
1.Cool-Front-End-Templates\Apple Webiste UI Clone
2.Cool-Front-End-Templates\Bloggers template
3.Cool-Front-End-Templates\basic_sigin_form
4.Cool-Front-End-Templates\Blog Page for any site
5.Cool-Front-End-Templates\ComingSoon
6.Cool-Front-End-Templates\Covid-19
7.Cool-Front-End-Templates\E commerce shopping website template
8.Cool-Front-End-Templates\Facebook Login Page Clone
9.Cool-Front-End-Templates\Food Website Template
10.Cool-Front-End-Templates\Food-Blog
11.Cool-Front-End-Templates\Food_Template
12.Cool-Front-End-Templates\Github_Homepage_Clone
13.Cool-Front-End-Templates\Glassmorphic Profile Card
14.Cool-Front-End-Templates\glassmorphism-form
15.Cool-Front-End-Templates\Home design
16.Cool-Front-End-Templates\Hotel Website
17.Cool-Front-End-Templates\Instagram Clone Frontend
18.Cool-Front-End-Templates\light-dark-LandingPage
19.Cool-Front-End-Templates-master\Maroom - Interior Design Landing Page
20.Cool-Front-End-Templates\Meet Landing Page
21.Cool-Front-End-Templates\Microsoft-Clone
22.Cool-Front-End-Templates\Neomorphic Portfolio
23.Cool-Front-End-Templates\netflixclone
24.Cool-Front-End-Templates\Newsletter
25.Cool-Front-End-Templates\Obatin - Medicine Landing Page
26.Cool-Front-End-Templates\Personal Website Landing Page
27.Cool-Front-End-Templates\portfolio Avinash
28.Cool-Front-End-Templates\PortFolio Template
29.Cool-Front-End-Templates\Price
30.Cool-Front-End-Templates\Profile-Tree (Linktree Alternative)
31.Cool-Front-End-Templates\Restaurant_Template
32.Cool-Front-End-Templates\simple dark form
33.Cool-Front-End-Templates\Social Media Dashboard
34.Cool-Front-End-Templates\Tourism Template
35.Cool-Front-End-Templates\Tailwind Portfolio
36.Cool-Front-End-Templates\Travel website template-1
37.Cool-Front-End-Templates\We design and develop
38.Cool-Front-End-Templates\web dev proj1 gym
39.Cool-Front-End-Templates\Welcome to lucknow
40.Cool-Front-End-Templates\Whatsapp
41.Cool-Front-End-Templates\Yoga template
42.Cool-Front-End-Templates\Yoga Template 2

- [x] Changed image format where preview was in **.jpeg/other image format** to **.png** format

- [x] Added images where preview.png was not there

**List is here:**
1.Cool-Front-End-Templates\Apple Webiste UI Clone
2.Cool-Front-End-Templates\ArtGalleryWebsite
3.Cool-Front-End-Templates\Auditions_Page
4.Cool-Front-End-Templates\basic_sigin_form
5.Cool-Front-End-Templates\Blog Page for any site
6.Cool-Front-End-Templates\Bloggers template
7.Cool-Front-End-Templates\Bootcamp Template
8.Cool-Front-End-Templates\Carousel_Landing_Page
9.Cool-Front-End-Templates\Digital Banking
10.Cool-Front-End-Templates\E commerce shopping website template
11.Cool-Front-End-Templates\Facebook Login Page Clone
12.Cool-Front-End-Templates\Food-Blog
13.Cool-Front-End-Templates\Footer-Template
14.Cool-Front-End-Templates\Game_Landing-master
15.Cool-Front-End-Templates\Github_Homepage_Clone
16.Cool-Front-End-Templates\Home design
17.Cool-Front-End-Templates\Instagram Clone Frontend
18.Cool-Front-End-Templates\light-dark-LandingPage
19.Cool-Front-End-Templates\Loaning Website
20.Cool-Front-End-Templates\login and signup page
21.Cool-Front-End-Templates\Meet Landing Page
22.Cool-Front-End-Templates\Microsoft-Clone
23.Cool-Front-End-Templates\Neomorphic Portfolio
24.Cool-Front-End-Templates\Netflix Home Page
25.Cool-Front-End-Templates\Personal Website Landing Page
26.Cool-Front-End-Templates\PortFolio Template
27.Cool-Front-End-Templates\Portfolio-Aryan
28.Cool-Front-End-Templates\Price
29.Cool-Front-End-Templates\Profile-Tree (Linktree Alternative)
30.Cool-Front-End-Templates\project2
31.Cool-Front-End-Templates\restaurant template
32.Cool-Front-End-Templates\Space Agency Template
33.Cool-Front-End-Templates\Starbucks Template
34.Cool-Front-End-Templates\Template Mobile Development Company
35.Cool-Front-End-Templates\Tourism Template
36.Cool-Front-End-Templates\tourism-portal\tourism
38.Cool-Front-End-Templates\Travel website template-1
39.Cool-Front-End-Templates\web dev proj1 gym
40.Cool-Front-End-Templates\WebsiteTemplate
41.Cool-Front-End-Templates\Welcome to lucknow
42.Cool-Front-End-Templates\Whatsapp
43.Cool-Front-End-Templates\Yoga template
44.Cool-Front-End-Templates\ZomatoClone

- [x] Added 1st letter of project capital and changed it in json file also

Fixes # (448)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:

- Operating system: Windows
- Version: 10
- Text-editors used: VS-Code

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by arpit456jain** [comment]
@TG922 pull the latest changes and push them

**Comment by TG922** [comment]
> @TG922 pull the latest changes and push them

Ok

**Comment by TG922** [comment]
**I recently checked that the below 3 conflicts created a new issue after the first PR for this issue !!**

Image11

**For the above 3 projects Image path is not synced!!**


**Results are shown below**

## Project 1: Cool-Front-End-Templates\AmolShelke-portfolio

Image10

## Project 2: Cool-Front-End-Templates\Pizza Corner

Image13

## Project 3: Cool-Front-End-Templates\GymWebsite

Image12

**I'm Sending PR after updating this**

**Comment by TG922** [comment]
- [x] Changed Starting Letter of the project to Capital Name in **json files**

List is here:
1. "name": "Engineers Copied Web",
    "link": "engineers copied web/index.html"

2."name": "Glassmorphism-Form",
    "link": "glassmorphism-form/index.html"

3."name": "Online Grocery- store",
    "link": "online grocery- store/index.html"

4."name": "Portfolio Avinash",
    "link": "portfolio Avinash/index.html"

5."name": "Simple Dark Form",
    "link": "simple dark form/index.html"

6."name": "Netflix Clone",
    "link": "netflixclone/index.html"

7. "name": "Gym Website",
      "link": "gymWebsite/index.html"

8. "name": "Sneaker Storefront",
      "link": "sneaker-storefront/index.html"


## Only This **Project 3: Cool-Front-End-Templates\GymWebsite** is having weird messages should I fix this @arpit456jain ??

**Style.css** File

Image15

****Index.html** File

Image14

**Comment by arpit456jain** [comment]
> * [x]  Changed Starting Letter of the project to Capital Name in **json files**
> 
> List is here:
> 
> 1. "name": "Engineers Copied Web",
>    "link": "engineers copied web/index.html"
> 
> 2."name": "Glassmorphism-Form", "link": "glassmorphism-form/index.html"
> 
> 3."name": "Online Grocery- store", "link": "online grocery- store/index.html"
> 
> 4."name": "Portfolio Avinash", "link": "portfolio Avinash/index.html"
> 
> 5."name": "Simple Dark Form", "link": "simple dark form/index.html"
> 
> 6."name": "Netflix Clone", "link": "netflixclone/index.html"
> 
> 7. "name": "Gym Website",
>    "link": "gymWebsite/index.html"
> 8. "name": "Sneaker Storefront",
>    "link": "sneaker-storefront/index.html"
> 
> ## Only This **Project 3: Cool-Front-End-Templates\GymWebsite** is having weird messages should I fix this @arpit456jain ??
> **Style.css** File
> 
> Image15
> 
> ****Index.html** File
> 
> Image14

@TG922   make sure that name and link must be same 

like u have

"name": "Engineers Copied Web",
"link": "engineers copied web/index.html"

it should be 
"name": "Engineers Copied Web",
"link": "Engineers Copied Web/index.html"

and must check the link of all templates it should not be broken

**Comment by arpit456jain** [comment]
@TG922 and add name and links of template which are not in json file yet

**Comment by DEEPALI-SUK** [comment]
@TG922 
1. In the Products Page folder, preview.png is not present.
2. Some folder names are not in the capital.
3. Look at the gym website; some code is written on the frontend.
4. In some folders like AmolShelke-portfolio, Mmm collections, Tailwind Portfolio, Travel website template-1, Gallery page of the Art gallery website, images are not linked correctly and are missing.
Check all the templates whether images are linked correctly or not.

**Comment by TG922** [comment]
> > * [x]   Changed Starting Letter of the project to Capital Name in **json files**
> > 
> > List is here:
> > 
> > 1. "name": "Engineers Copied Web",
> >    "link": "engineers copied web/index.html"
> > 
> > 2."name": "Glassmorphism-Form", "link": "glassmorphism-form/index.html"
> > 3."name": "Online Grocery- store", "link": "online grocery- store/index.html"
> > 4."name": "Portfolio Avinash", "link": "portfolio Avinash/index.html"
> > 5."name": "Simple Dark Form", "link": "simple dark form/index.html"
> > 6."name": "Netflix Clone", "link": "netflixclone/index.html"
> > 
> > 7. "name": "Gym Website",
> >    "link": "gymWebsite/index.html"
> > 8. "name": "Sneaker Storefront",
> >    "link": "sneaker-storefront/index.html"
> > 
> > ## Only This **Project 3: Cool-Front-End-Templates\GymWebsite** is having weird messages should I fix this @arpit456jain ??
> > **Style.css** File
> > Image15
> > ****Index.html** File
> > Image14
> 
> @TG922 make sure that name and link must be same
> 
> like u have
> 
> "name": "Engineers Copied Web", "link": "engineers copied web/index.html"
> 
> it should be "name": "Engineers Copied Web", "link": "Engineers Copied Web/index.html"
> 
> and must check the link of all templates it should not be broken

Ok @arpit456jain

**Comment by TG922** [comment]
> @TG922
> 
> 1. In the Products Page folder, preview.png is not present.
> 2. Some folder names are not in the capital.
> 3. Look at the gym website; some code is written on the frontend.
> 4. In some folders like AmolShelke-portfolio, Mmm collections, Tailwind Portfolio, Travel website template-1, Gallery page of the Art gallery website, images are not linked correctly and are missing.
>    Check all the templates whether images are linked correctly or not.

Ok I will see

**Comment by arpit456jain** [comment]
@TG922 take ur time there is no hurry .

if this works well u can do same in other 2 repos with lvl 3 label

**Review by astha2412 — CHANGES_REQUESTED** [review]
Make necessary changes

**Comment by TG922** [comment]
## Do check the Missing project mentioned in the JSON file

{
      "name": "Artica",
      "link": "Artica/index.html"
    },

## There were 2 **Netflix Clone**, so I renamed 2nd one as **Netflix Clone-2**

Image24

## Colon ":" Named Folder not allowed so replaced it with "-" on both the JSON and folder

{
      "name": "Moninfo:Indian Monuments Template",
      "link": "Moninfo:Indian Monuments Template/index.html"
    },

## Do check this Image folder!! Don't know for which file it belongs to

Image25

## Mmm Collections have uploaded the wrong online image URL

- [x] make sure that name and link must be same



> @TG922
> 
> 1. In the Products Page folder, preview.png is not present.
> 2. Some folder names are not in the capital.
> 3. Look at the gym website; some code is written on the frontend.
> 4. In some folders like AmolShelke-portfolio, Mmm collections, Tailwind Portfolio, Travel website template-1, Gallery page of the Art gallery website, images are not linked correctly and are missing.
>    Check all the templates whether images are linked correctly or not.

- [x] Changes Done

**Comment by DEEPIKA-SUK** [comment]
@TG922 1. In Food Website Template main background image is missing, see the preview.png.
2. In money website one header color is not matching with preview.png
3. Tailwind Portfolio men images ka problem hai.
4. Technology page men header header match nhi ho raha preview se.
5. In gym website code is written in frontend.
Kindly make these changes.

**Comment by arpit456jain** [comment]
@TG922 do this changes asap and then we are good to go

**Comment by TG922** [comment]
Ok I will do it today I was having exam

**Comment by arpit456jain** [comment]
@TG922

**Comment by TG922** [comment]
OK I'm on it will send PR within some hour

**Comment by TG922** [comment]
I don't know you are really a girl but I would really like to appreciate @DEEPALI-SUK and @DEEPIKA-SUK  for pointing out issues !! It is not easy to point out issues in all projects.
Most of the time I was surprised with the issues **Are ye kaise reh gaya??**

**Review by VidhiBhatt01 — APPROVED** [review]
@arpit456jain LGTM but still cross-verify it once with some other mentor

**Review by DEEPALI-SUK — APPROVED** [review]

**Review by arpit456jain — APPROVED** [review]

**Pull request merged**
