### PR TITLE
changed the design of footer along with background image

### PR DESCRIPTION
**Pull request by myhacktech**
# Description

changed the background-color of footer ,so that it matches with theme
added social media icon using map tool
Fixes:  #554

## Type of change

- [x ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ x] I have made this from my own
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
Screenshot (276)
- [x ] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Review by DEEPIKA-SUK — APPROVED** [review]

**Comment by DEEPIKA-SUK** [comment]
@myhacktech fix this issue.
Screenshot (104)
make the footer for entire width of the screen.

**Comment by myhacktech** [comment]
> @myhacktech fix this issue. Screenshot (104) make the footer for entire width of the screen.

Ok

**Comment by myhacktech** [comment]
@DEEPIKA-SUK please review this...

**Comment by VidhiBhatt01** [comment]
And yes, keep the same font style same throughout the website and write Maroom in bold the way it is written in navbar

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
image
Almost perfect! There's some text showing up above the footer which says adobe stock. Can you remove/hide/fix it?

**Comment by VidhiBhatt01** [comment]
https://deploy-preview-583--cool-front-end-templates.netlify.app/maroom%20-%20interior%20design%20landing%20page/

**Review by VidhiBhatt01 — APPROVED** [review]
Perfect!

**Pull request merged**
