### PR TITLE
Fixed the navbar of HotelWebsite #506

### PR DESCRIPTION
**Pull request by kanikakaur27**
# Description

Fixed the navbar of the HotelWebsite

Fixes:  #506 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
demo

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
You need to attach all the files of the Hotel Website to this PR. Then and only then I will be able to verify the changes.

**Comment by kanikakaur27** [comment]
@VidhiBhatt01 I have posted my query on the discord channel. please let me know regarding the same.

**Comment by kanikakaur27** [comment]
@VidhiBhatt01 kindly have a look now. thanks.

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
The navbar is not responsive :(

image

**Comment by VidhiBhatt01** [comment]
https://deploy-preview-525--cool-front-end-templates.netlify.app/hotel%20website/

**Pull request closed without merging**
