### PR TITLE
responsive website for university

### PR DESCRIPTION
**Pull request by YatreeLadani**
# Description

I have made a fully responsive university landing page. 

issue no:-  #776 

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resources 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas

# ATTACH SCREEN-SHOTS 
image

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Just fix this section, rest all is refect.
image

**Comment by arpit456jain** [comment]
image


increase the width of cards: 
image


make it in center
image

**Review by DEEPIKA-SUK — CHANGES_REQUESTED** [review]
@YatreeLadani add your project in style_links.json file. And do all the changes by tomorrow night.

**Comment by YatreeLadani** [comment]
> @YatreeLadani add your project in style_links.json file. And do all the changes by tomorrow night.

@DEEPIKA-SUK  it's done.

**Review by VidhiBhatt01 — APPROVED** [review]

**Pull request merged**
