### PR TITLE
Added frontend blog website 'BlogsWorld'  #576

### PR DESCRIPTION
**Pull request by TadrupDas**
# Description
want to contribute the frontend of a blog website.  #576 

Added the frontend of a blog website created by me, named "BlogsWorld".

BlogsWorld

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Link the issue in description

**Comment by TadrupDas** [comment]
Done.

**Comment by DEEPIKA-SUK** [comment]
Screenshot (121)
Make it responsive.

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
This isn't a proper way to fix responsiveness. It must be like
Card1
Card2
rather than card1 card 2 in same line
image


Also, the image URLs are broken

**Comment by VidhiBhatt01** [comment]
https://deploy-preview-717--cool-front-end-templates.netlify.app/blogsworld/

**Comment by DEEPIKA-SUK** [comment]
@TadrupDas fix this
Screenshot (127)

**Comment by DEEPIKA-SUK** [comment]
@TadrupDas do the changes by today.

**Comment by DEEPIKA-SUK** [comment]
@TadrupDas also add this project in style_links.json file.

**Comment by DEEPIKA-SUK** [comment]
@TadrupDas it is still not responsive
Screenshot (128)
Since this PR is open from so long do the changes by tomorrow afternoon otherwise I will close this PR.

**Comment by DEEPIKA-SUK** [comment]
@TadrupDas any updates?

**Pull request closed without merging**
