### PR TITLE
Template for Podcast Website - PsychoPod Website

### LINKED ISSUE #379: Template for Podcast Website - PsychoPod Website
## Issue Type:

- [x] Project Addition
## **Possible solution**

- This can be used as template for Psychology Podcast providing companies. They can use it as a Landing Page/Website to showcase their services provided.

### PR DESCRIPTION
**Pull request by priyanshi1282**
# Description

Added a new Website Template - Psychology Podcast Website : Psychopod Website.

Fixes #379

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# Explain the Testing instructions

**Test Configuration**:
- Text-editors used: VS Code

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

Screenshot (75)
Screenshot 2022-03-11 223053
Screenshot 2022-03-11 223114
Screenshot 2022-03-11 222953
Screenshot 2022-03-11 223026

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Make it responsive.

image

**Comment by priyanshi1282** [comment]
ok @VidhiBhatt01, within 2-3days I will be  updating it.

**Comment by arpit456jain** [comment]
@priyanshi1282

**Comment by priyanshi1282** [comment]
### Hey @VidhiBhatt01 , @arpit456jain  I have updated the template to responsive one. Please check once and let me know still any changes required 😀.

**Pull request merged**
