### PR TITLE
Made template responsive and added transition in dialing icon

### PR DESCRIPTION
**Pull request by myhacktech**
# Description
Items aligned properly in template and made responsive ,also introduced transition in telephone icon

Fixes:  #(issue no.)https://github.com/arpit456jain/Cool-Front-End-Templates/issues/460

460 

## Type of change

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)

# Checklist:

- [ x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

- [x ] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot (265)
Screenshot (266)
Screenshot (267)

### CODE REVIEW

**Comment by myhacktech** [comment]
@VidhiBhatt01 please review my PR  request...

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
None of the images are being loaded. Just fix it and then I will approve it.

image

Also, add this project in style_links.json

**Comment by myhacktech** [comment]
> None of the images are being loaded. Just fix it and then I will approve it.
> 
> image
> 
> Also, add this project in style_links.json



> None of the images are being loaded. Just fix it and then I will approve it.
> 
> image
> 
> Also, add this project in style_links.json

ok ,i think i forget to add that.

**Comment by myhacktech** [comment]
@VidhiBhatt01 Please check now,I tried uploading files properly.

**Review by VidhiBhatt01 — APPROVED** [review]

**Pull request merged**
