### PR TITLE
Improved Website - Refactored the Images and Broken Sections

### PR DESCRIPTION
**Pull request by hariketsheth**
# Description
- Updated Social media Icons 
- Added Fallback Image which would be displayed when image given by user fails to load or doesn't exist

Fixes:  #(issue no.)
#841

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image

Review required @arpit456jain

### CODE REVIEW

**Review by VidhiBhatt01 — COMMENTED** [review]
Were there so many projects without an image!?
image

**Comment by hariketsheth** [comment]
> Were there so many projects without an image!? image

Yes, that's why I took up this work.

**Comment by VidhiBhatt01** [comment]
Ahh okay, let's wait till some other mentor reviews this. This on is a crucial PR

**Review by DEEPIKA-SUK — APPROVED** [review]

**Review by VidhiBhatt01 — APPROVED** [review]

**Comment by VidhiBhatt01** [comment]
@hariketsheth can you do the same thing for our other 2 repos?

**Comment by hariketsheth** [comment]
> @hariketsheth can you do the same thing for our other 2 repos?

I will do that. But I wanted to request 2 things. 
1. Will this PR be merged , or we still would wait for the 3 pending reviewers ? 
2. Can you assign me some issue / work to be done on this repository, since I want to make more contributions. So if you can suggest me some `Level 3` or `Level 2` type contributions, I would surely work on it and complete asap. 

Thanks @VidhiBhatt01

**Comment by VidhiBhatt01** [comment]
PA will merge this issue soon, you will get level 3 on this PR and level 2 on the PRs of the other two repos. Just raise the issue in both the repos and tag me there, I will assign them to you ASAP

**Review by arpit456jain — APPROVED** [review]

**Comment by hariketsheth** [comment]
@arpit456jain @VidhiBhatt01 This was a Level 3 PR, but the label added was of Level 2. Kindly check please.

**Pull request merged**
