### PR TITLE
Issue Number #206 Assigned to me is completed. I have added the landing page for a travel website

### PR DESCRIPTION
**Pull request by Vedant-Jayesh-Oza**
# Description

Hey @astha2412, @arpit456jain Issue number #206 assigned to me is completed Added the landing page. Attaching some images.

Fixes # (issue no.)

#206 

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image
image
image

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Make it responsive

image

**Comment by Vedant-Jayesh-Oza** [comment]
Okay will do it !

**Comment by astha2412** [comment]
@Vedant-Jayesh-Oza Make changes fast!

**Comment by Vedant-Jayesh-Oza** [comment]
@astha2412 I had a word with @VidhiBhatt01 Regarding this PR, please contact her. I apologize for the inconvenience.

**Comment by arpit456jain** [comment]
no problem @Vedant-Jayesh-Oza  just make a new PR when u r ready

**Pull request closed without merging**
