### PR TITLE
Added Email Authentication Method

### PR DESCRIPTION
**Pull request by Abh1shekSingh**
# Description

I have added Email Authentication method. I have attached screenshot for your Reference.
User can signup wit his email an password and then if he came later he can use the same id password to login back.
Its also display the name or email, depends what he has in the json, on the top of screen.

Fixes:  #811 

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
after succes signup
after success login with same idpsd
firebase

### CODE REVIEW

**Comment by Abh1shekSingh** [comment]
@VidhiBhatt01 @astha2412 @DEEPIKA-SUK Please review my PR

**Review by DEEPIKA-SUK — APPROVED** [review]

**Review by DEEPIKA-SUK — CHANGES_REQUESTED** [review]
@Abh1shekSingh after login also it is showing welcome username in the same login page. So add one more page for welcome or disable that login form after login.

**Comment by Abh1shekSingh** [comment]
> @Abh1shekSingh after login also it is showing welcome username in the same login page. So add one more page for welcome or disable that login form after login.

My job was to add authentication only. and display the name.

**Comment by DEEPIKA-SUK** [comment]
> > @Abh1shekSingh after login also it is showing welcome username in the same login page. So add one more page for welcome or disable that login form after login.
> 
> My job was to add authentication only. and display the name.

@Abh1shekSingh because of this login form the person can login multiple times even they are already logged in. So disable login button or hide this login form and add one logout functionality also.

**Comment by Abh1shekSingh** [comment]
> > > @Abh1shekSingh after login also it is showing welcome username in the same login page. So add one more page for welcome or disable that login form after login.
> > 
> > 
> > My job was to add authentication only. and display the name.
> 
> @Abh1shekSingh because of this login form the person can login multiple times even they are already logged in. So disable login button or hide this login form and add one logout functionality also.


> > > @Abh1shekSingh after login also it is showing welcome username in the same login page. So add one more page for welcome or disable that login form after login.
> > 
> > 
> > My job was to add authentication only. and display the name.
> 
> @Abh1shekSingh because of this login form the person can login multiple times even they are already logged in. So disable login button or hide this login form and add one logout functionality also.

Will add Sign Out Functionality in my other PR #810  and #809

**Comment by Abh1shekSingh** [comment]
@DEEPIKA-SUK Please review now, i have done the required changes

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
style_links.json update karo

**Comment by Abh1shekSingh** [comment]
> style_links.json update karo

Yeh, Already existed project hai aapka. Usme authentication add ki hai mene

**Comment by DEEPIKA-SUK** [comment]
> > > > @Abh1shekSingh after login also it is showing welcome username in the same login page. So add one more page for welcome or disable that login form after login.
> > > 
> > > 
> > > My job was to add authentication only. and display the name.
> > 
> > 
> > @Abh1shekSingh because of this login form the person can login multiple times even they are already logged in. So disable login button or hide this login form and add one logout functionality also.
> 
> > > > @Abh1shekSingh after login also it is showing welcome username in the same login page. So add one more page for welcome or disable that login form after login.
> > > 
> > > 
> > > My job was to add authentication only. and display the name.
> > 
> > 
> > @Abh1shekSingh because of this login form the person can login multiple times even they are already logged in. So disable login button or hide this login form and add one logout functionality also.
> 
> Will add Sign Out Functionality in my other PR #810 and #809 . @DEEPIKA-SUK I will add A signout button on Welcome Page which will allow user to get sign out and redirect to login form back

Okay rest is good.

**Review by DEEPIKA-SUK — APPROVED** [review]

**Pull request merged**
