### PR TITLE
Payment Gateway Added

### PR DESCRIPTION
**Pull request by Kunal0220**
# Description

This is a Payment Template which can be linked with any merchant to accept payments via different options like Credit/Debit Card , UPI or even Internet banking . It's just the frontend so the backend has to be linked along with the SSL certificates and other stuffs.

This repository just needs to be cloned and there you are home boy , You can run it on your server or attach to any existing website .

Fixes:  #807 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

Video:
https://user-images.githubusercontent.com/71934168/168591022-ac8f970c-a831-4c00-8558-c28675c77b2e.mp4

Deployment Link:
https://kunal0220.github.io/PaymentGateway/

Future plans:
I would like to make it into an SPA in the near future and add Dark and Light mode to it .

### CODE REVIEW

**Review by DEEPIKA-SUK — CHANGES_REQUESTED** [review]
@Kunal0220 add this project in style_links.json file, make it responsive.

**Comment by Kunal0220** [comment]
hey @DEEPIKA-SUK , I have made the changes , If you want I'll attach some pictures of the updated Website.

**Comment by DEEPIKA-SUK** [comment]
https://deploy-preview-828--cool-front-end-templates.netlify.app/payment_gateway/

**Comment by Kunal0220** [comment]
Please add a Level to it .

**Comment by DEEPIKA-SUK** [comment]
> Please add a Level to it .

It will be added by PA.

**Comment by Kunal0220** [comment]
Hey I have made it responsive to all the pixels specified in the chrome developer environment.
Screenshot 2022-05-17 at 4 26 26 PM
Screenshot 2022-05-17 at 4 26 36 PM
Screenshot 2022-05-17 at 4 26 42 PM
Screenshot 2022-05-17 at 4 26 48 PM
Screenshot 2022-05-17 at 4 26 53 PM
Screenshot 2022-05-17 at 4 26 59 PM

**Comment by Kunal0220** [comment]
Any more changes required?

**Comment by DEEPIKA-SUK** [comment]
> I saw the breaking point sir , I'll be right back.🙌🏻 Thanks for your time and patience.

I am a girl 😅

**Review by DEEPIKA-SUK — APPROVED** [review]

**Comment by Kunal0220** [comment]
> > I saw the breaking point sir , I'll be right back.🙌🏻 Thanks for your time and patience.
> 
> I am a girl 😅
m sorry , my bad✌🏻

**Pull request merged**
