### PR TITLE
Updated Medeasy notes website template

### PR DESCRIPTION
**Pull request by priyanshi1282**
# Description
Updated Website by adding About and Contact Us section to it.

Fixes:  #615 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
#### Final Website after Updating.
home
about
services
contribute
contactus

### consider this under GSSoC'22 contribution.

### CODE REVIEW

**Comment by arpit456jain** [comment]
@priyanshi1282

**Comment by priyanshi1282** [comment]
> @priyanshi1282

Yes?

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
https://deploy-preview-626--cool-front-end-templates.netlify.app/medeasy%20website/

Just resolve the merge conflicts

**Comment by priyanshi1282** [comment]
@VidhiBhatt01 I have resolved the conflicts, please check once.

**Pull request merged**
