### PR TITLE
Added Clone Of the Website " Go Daddy "

### PR DESCRIPTION
**Pull request by eswarbhageerath**
This is the PR of the issue Go Daddy Website Clone #725...
Please review sir/mam.
Thank you.

### CODE REVIEW

**Comment by DEEPIKA-SUK** [comment]
@eswarbhageerath you have build this by your own? Kindly link the resources you have taken for your reference in the description.

**Comment by eswarbhageerath** [comment]
@DEEPIKA-SUK I have made this on my own, I followed this course step by step in making this project.

https://www.udemy.com/course/the-complete-web-development-bootcamp/

This is a beginner-friendly course. In The project, All the web designing part  I used in this project was the reference to This course.

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
https://deploy-preview-726--cool-front-end-templates.netlify.app/go%20daddy%20website%20clone/

Add the reference video link in readme file

**Review by VidhiBhatt01 — APPROVED** [review]

**Comment by eswarbhageerath** [comment]
@VidhiBhatt01 I have updated the readme.md file accordingly.

**Review by DEEPIKA-SUK — APPROVED** [review]

**Pull request merged**
