### PR TITLE
fixed extra space and centered the template , displayed a templates in tablet view...

### PR DESCRIPTION
**Pull request by codingkush**
# Description

extra space left side of website and templates were not center

Fixes:  #597 

## Type of change

fixed extra space  and centered the templates  -------------->

newq

displayed a ( two )  templates in tablet view --------------->

tablett

### CODE REVIEW

**Comment by arpit456jain** [comment]
@codingkush merge conflicts

**Comment by codingkush** [comment]
Done

**Comment by codingkush** [comment]
Done

**Comment by codingkush** [comment]
Done

**Review by VidhiBhatt01 — COMMENTED** [review]
approved

**Pull request merged**
