### PR TITLE
Added Technical documentation page.

### PR DESCRIPTION
**Pull request by AmolShelke2**
# Description

Hey, project admin, as you assigned me this issue to work on I have created the pull request regarding that, I have added a Technical documentation website created with HTML and CSS to the current repository please go through the pull request and review it. thanks.

Fixes:  #820 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
documentpage-free-code-camp vercel app_

@DEEPIKA-SUK please review this pull request.

### CODE REVIEW

**Comment by VidhiBhatt01** [comment]
https://deploy-preview-834--cool-front-end-templates.netlify.app/tech-landing-page/

**Comment by AmolShelke2** [comment]
> Can we have navbar for this section? image
> 
> Also are you sure you made it on your own!? 👀

@VidhiBhatt01 here is the repository and I haven't written all those documentation on my own I just copied it from the WEB MDN docs 
[Tech-doc-page](https://github.com/AmolShelke2/Documentpage.FreeCodeCamp.git)

**Comment by AmolShelke2** [comment]
@VidhiBhatt01 has done the changes. I have tried to make it as possible as I can. please go through the changes.

**Review by DEEPIKA-SUK — CHANGES_REQUESTED** [review]
@AmolShelke2 remove this extra space.
Screenshot 2022-05-18 203028

**Review by VidhiBhatt01 — APPROVED** [review]
That's the scroll bar @DEEPIKA-SUK 🙃

**Comment by AmolShelke2** [comment]
Yes it is the scroll bar there if you click the menu icon the nav will open
that's how I Created the navnar section

**Comment by AmolShelke2** [comment]
@arpit456jain please review krdo pull request.

**Pull request merged**
