### PR TITLE
Medicare

### PR DESCRIPTION
**Pull request by DragonUncaged**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #729

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
I think you have linked wrong issue

**Comment by DragonUncaged** [comment]
> I think you have linked wrong issue

Done !! #729

**Comment by DEEPIKA-SUK** [comment]
@DragonUncaged 
Screenshot 2022-05-05 234106
Remove this extra white space.

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
1. Style_links.json
2. Remove horizontal scroll
image
3. Make it properly responsive

**Comment by VidhiBhatt01** [comment]
https://deploy-preview-743--cool-front-end-templates.netlify.app/medical%20insurance/

**Comment by DEEPIKA-SUK** [comment]
> 1. Style_links.json
> 2. Remove horizontal scroll
>    image
> 3. Make it properly responsive

these problems are still there @DragonUncaged

**Comment by DragonUncaged** [comment]
> > 1. Style_links.json
> > 2. Remove horizontal scroll
> >    image
> > 3. Make it properly responsive
> 
> these problems are still there @DragonUncaged

Done !!

**Comment by DragonUncaged** [comment]
> 
> Done !!

**Review by DEEPIKA-SUK — APPROVED** [review]

**Comment by DEEPIKA-SUK** [comment]
@DragonUncaged correct the link in style_links.json file.

**Comment by DragonUncaged** [comment]
> @DragonUncaged correct the link in style_links.json file.

Done!!

**Review by DEEPIKA-SUK — APPROVED** [review]

**Pull request merged**
