### PR TITLE
College frontEnd webpage  #296

### PR DESCRIPTION
**Pull request by Ankitsingh2001**
issue no.  #296

### CODE REVIEW

**Review by VidhiBhatt01 — APPROVED** [review]
@Ankitsingh2001 are you sure that you made it on your own?

**Comment by Ankitsingh2001** [comment]
> @Ankitsingh2001 are you sure that you made it on your own?

it's made by me but  some parts, in this page layout, suggest my friend and all code is mine

**Comment by Ankitsingh2001** [comment]
> @Ankitsingh2001 are you sure that you made it on your own?

it's made by me but  some parts, in this page layout, suggest my friend and all code is mine

**Review by VidhiBhatt01 — COMMENTED** [review]
https://www.youtube.com/watch?v=6Mgyufh46gM

**Pull request merged**
