### PR TITLE
Resolve Chines Restaurant  website Responsiveness .

### PR DESCRIPTION
**Pull request by AsmaIbrahimButt**
# Description

I resolved the responsiveness of a website.

Fixes:  #676

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have made this from my own
- [ ] I have taken help from some online resourses 
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
first
seconds
tjird
four
five

### CODE REVIEW

**Review by DEEPIKA-SUK — APPROVED** [review]

**Comment by arpit456jain** [comment]
@AsmaIbrahimButt merge conflicts

**Review by DEEPALI-SUK — COMMENTED** [review]
There are some extra files delete those files and also resolve the merge conflicts

**Comment by AsmaIbrahimButt** [comment]
@DEEPALI-SUK can u plz guide me i dont know whats happened when i make changes it looks perfect on my local machine plus when i make a pull request there is no merge conflict after some time it show there is merge conflict even i resolve it number of times .Why this happened?

**Comment by AsmaIbrahimButt** [comment]
@DEEPIKA-SUK I thin I have to close this pull request and make changes again and make a new pull request in this way may b this issue resolve?What do u think about it?Looking forward of ur response.

**Comment by DEEPIKA-SUK** [comment]
> @DEEPIKA-SUK I think I have to close this pull request and make changes again and make a new pull request in this way may b this issue resolve?What do u think about it?Looking forward of ur response.

Make a new PR.

**Pull request closed without merging**
