### PR TITLE
added Pizza rest New Interface

### PR DESCRIPTION
**Pull request by Abh1shekSingh**
# Description

Added New Interface of the website

Fixes:  #833 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
pizza4
pizza3
pizza2
pizza1

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
image
Resoponsive nahi hai so ek level kam milega, you want to fix it ya raise hi rakhe?

**Comment by VidhiBhatt01** [comment]
https://deploy-preview-878--cool-front-end-templates.netlify.app/pizza%20corner/

**Comment by Abh1shekSingh** [comment]
@VidhiBhatt01  again the same thing...huh.... Once you will merge it, it won't show any errors vidhi. It will be properly aligned and there will be no horizontal scroll.

**Comment by VidhiBhatt01** [comment]
But this ain't about horizontal scroll

**Comment by VidhiBhatt01** [comment]
But this ain't about horizontal scroll🙃

**Comment by arpit456jain** [comment]
> https://deploy-preview-878--cool-front-end-templates.netlify.app/pizza corner

ok will merge it for now giving lvl2 will check it once it gets merged if its fine i will increase the lvl

**Comment by arpit456jain** [comment]
nope its not perfect lvl2 is fine

**Comment by arpit456jain** [comment]
@Abh1shekSingh  i told u before not to make changes in old template 
add it as a new template in a new folder with a different name

**Comment by Abh1shekSingh** [comment]
> nope its not perfect lvl2 is fine

Kya perfection nhi hai?

**Pull request merged**
