### PR TITLE
Hysky Responsive community Portfolio web

### PR DESCRIPTION
**Pull request by yash-25log**
## Description 📜

responsive website build
using html css js

This website can be used by any club in robotics
This mainly promotes any robotic teams service like a portfolio website

issue #690   solved

<hr />

## Domain of Contribution 📊

- [x] HTML, CSS, JS

<hr />
 
## Checklist ✅

- [x] I follow [Code of conduct](https://github.com/surajm-333/Ace-The-FrontEnd/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added required screenshot/gif depicting the working of the project in the folder
- [x] I am a GSSoC'22 contributor

<hr />

## Screenshots / Gif 📸
image
image
image

### CODE REVIEW

**Comment by yash-25log** [comment]
@arpit456jain @VidhiBhatt01 https://github.com/surajm-333/Ace-The-FrontEnd/pull/368

**Comment by yash-25log** [comment]
@VidhiBhatt01 @arpit456jain https://hysky-web.vercel.app/

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Remove horizontal scrolling
image

Also, did you make it totally on your own?👀

**Comment by VidhiBhatt01** [comment]
https://deploy-preview-693--cool-front-end-templates.netlify.app/hysky%20website/

**Comment by yash-25log** [comment]
> Remove horizontal scrolling image
> 
> Also, did you make it totally on your own?👀

just keep adding all mini projects inside one project

thou assets aren't mine

**Review by VidhiBhatt01 — APPROVED** [review]

**Comment by yash-25log** [comment]
@VidhiBhatt01 check now

**Comment by yash-25log** [comment]
@arpit456jain

**Comment by yash-25log** [comment]
Sry for trouble

**Pull request closed without merging**
