### PR TITLE
Fixed issue #394

### LINKED ISSUE #394: Make Food Ordering Website Responsive
## Issue Type:

- [X] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Tasks**
 [1] Fix the nav bar
 
image

[2] Size this section properly
image

[3] Improve the UI of the footer(You can change it completely too)
image

### PR DESCRIPTION
**Pull request by juberiya1ajaz**
# Description
Fixes #394

changed the footer and its style 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Explain the Testing instructions

**Test Configuration**:

- Operating system:64-bit operating system, x64-based processor
- Version:windows 11
- Text-editors used: VS code

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
#footer 
image

# responsive footer
image

#responsiveness of contact us
image

### CODE REVIEW

**Comment by juberiya1ajaz** [comment]
I am a gssoc participants , so kindly add  the required tags .

**Review by astha2412 — COMMENTED** [review]
https://deploy-preview-474--cool-front-end-templates.netlify.app/food%20ordering/

**Comment by astha2412** [comment]
Looks fine !

**Comment by arpit456jain** [comment]
@juberiya1ajaz  

mention the correct issue

**Comment by juberiya1ajaz** [comment]
The issue was ui of the footer as well as its responsiveness.

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Fix this too

image

image

**Comment by VidhiBhatt01** [comment]
Contact us is getting cut

**Comment by juberiya1ajaz** [comment]
will do it soon .

**Comment by juberiya1ajaz** [comment]
@VidhiBhatt01 i had resolved the contact us issue but I am unable to compare and create pr . I  do not know why this is happening. I was able to create pr and compare with my branch before.

**Comment by juberiya1ajaz** [comment]
I had resolved the contact us issue.

**Review by DEEPIKA-SUK — APPROVED** [review]

**Review by arpit456jain — APPROVED** [review]

**Comment by juberiya1ajaz** [comment]
Can anyone tell me why this issue does not have a label tag of levels?

**Pull request merged**
