### PR TITLE
Added Organic Retail Website Template

### PR DESCRIPTION
**Pull request by kaustav202**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #480 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

preview

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Text is very small. Fix it and make it responsive for all screen sizes. Also, did you totally make it on your own?

image

**Comment by VidhiBhatt01** [comment]
https://deploy-preview-646--cool-front-end-templates.netlify.app/organic%20retail%20website%20template/

**Comment by kaustav202** [comment]
@VidhiBhatt01 I've made the changes. Yes It's made by me only.

**Comment by arpit456jain** [comment]
> @VidhiBhatt01 I've made the changes. Yes It's made by me only.

@kaustav202 its looking good just increase font size of headings in small screen and adjust the extra spaces

**Comment by kaustav202** [comment]
> > @VidhiBhatt01 I've made the changes. Yes It's made by me only.
> 
> @kaustav202 its looking good just increase font size of headings in small screen and adjust the extra spaces

@arpit456jain  done. It's fully responsive for mobile devices now please check.

**Review by arpit456jain — APPROVED** [review]

**Pull request merged**
