### PR TITLE
Animated website

### PR DESCRIPTION
**Pull request by RajAdwaita**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
I have added a new Frontend Template to this repository that requires no previously downloaded packages or modules. To run it just click on the index.html file and you are good to go.

Fixes:  #(issue no.)
#444 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot 2022-03-17 213327
Screenshot 2022-03-23 155431
Screenshot 2022-03-23 155459
Screenshot 2022-03-23 155517
Screenshot 2022-03-23 155532
Screenshot 2022-03-23 155552

### CODE REVIEW

**Comment by RajAdwaita** [comment]
Maam I made this on my own

**Comment by RajAdwaita** [comment]
Could you please check , I just removed the movie website from this branch

**Review by VidhiBhatt01 — APPROVED** [review]
Perfect, just add this project in style_links.json too and push the changes

**Comment by RajAdwaita** [comment]
hey could you please check these conflicting issues

**Pull request merged**
