### PR TITLE
Template for Cake Shop Website

### PR DESCRIPTION
**Pull request by coolblizzarts**
I have created a website for a Cake Shop with a gallery and a customer review page.

# Description

This is a website template for a cake shop. It consists of the cake menu, cake picture gallery and a customer review page.

Fixes:  #(802)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by coolblizzarts** [comment]
Template for the cake shop website.

**Comment by coolblizzarts** [comment]
I have also made another pull request containing the updated style_links.json file but it didn't get merged with the previous pull request since I don't have the write access to this repository.

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
1. Remove extra space
image


2. Resolve merge conflicts
3. Make this responsive too
image
4. Add a preview.png img which can be used as a preview img on the main site

Lastly, are you sure you made it on your own?

**Comment by VidhiBhatt01** [comment]
> I have also made another pull request containing the updated style_links.json file but it didn't get merged with the previous pull request since I don't have the write access to this repository.

Am not getting you

**Review by VidhiBhatt01 — COMMENTED** [review]
@coolblizzarts

**Comment by coolblizzarts** [comment]
> 1. Remove extra space
>    image
> 2. Resolve merge conflicts
> 3. Make this responsive too
>    image
> 4. Add a preview.png img which can be used as a preview img on the main site
> 
> Lastly, are you sure you made it on your own?

Hello, will make all the changes mentioned. Actually I am a beginner to the concept of website development so I took online references but the template has been created by me. 

Also, I have already added a preview image file named 
preview
preview.img

**Comment by coolblizzarts** [comment]
> > I have also made another pull request containing the updated style_links.json file but it didn't get merged with the previous pull request since I don't have the write access to this repository.
> 
> Am not getting you

I am trying to merge a 2nd pull request that I made after the 1st full request. For the 1st pull request I had added all the files related to the cake shop website template. In the 2nd pull request I had uploaded the 'style_links.json' file because I had forgotten to attach it 
pull request merge error
to the 1st pull request. However, I am not able to merge the 1st and 2nd pull request because I am not the admin.

**Review by VidhiBhatt01 — COMMENTED** [review]
Close this PR and make a new one, with different branch

**Comment by DEEPIKA-SUK** [comment]
@coolblizzarts do all the changes by tomorrow

**Review by DEEPIKA-SUK — COMMENTED** [review]
@coolblizzarts do all the changes by tomorrow

**Pull request closed without merging**
