### PR TITLE
Update food.css

### PR DESCRIPTION
**Pull request by vandana3869**
# Description

Fixed the header of the food blog website

Fixes:  #505

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

Before
Screenshot 2022-04-11 174747
After
Screenshot 2022-04-11 173422

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Push the index.html file too of this project in this PR. Then and only then I will be able to verify the changes.

**Comment by vandana3869** [comment]
@VidhiBhatt01 added the index.html ....please review

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
You need to make it responsive.
image


Also, these buttons must be on the end.
image




https://deploy-preview-624--cool-front-end-templates.netlify.app/food-blog/food%20page

**Comment by vandana3869** [comment]
Issues fixed

Buttons are on the end
Screenshot 2022-04-16 022601

Made it responsive
Screenshot 2022-04-16 022145

**Comment by vandana3869** [comment]
@VidhiBhatt01 Please review this... thanks :)

**Comment by arpit456jain** [comment]
@vandana3869 the header is not responsive at all make a new PR when its fully ready

**Comment by vandana3869** [comment]
@arpit456jain thanks....sir can please suggest what changes I should make to make it more responsive

**Pull request closed without merging**
