### PR TITLE
 #281 i have added cartoon image  with  motivational  thoughts

### PR DESCRIPTION
**Pull request by Khushbu-kumari-87090**
i have added cartoon image with motivational thoughts.

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (281.)

## i have added cartoon image with motivational thoughts

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:

- Operating system:
- Version:
- Text-editors used:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by Khushbu-kumari-87090** [comment]
i have added cartoon image with motivational thoughts front end page .

**Comment by Khushbu-kumari-87090** [comment]
i have added cartoon  image with motivational thoughts.

**Comment by VidhiBhatt01** [comment]
@Khushbu-kumari-87090 the CSS is not getting displayed on the deployed link. Kindly look into that and fix it

**Comment by VidhiBhatt01** [comment]
Also, resolve the merge conflicts

**Comment by Khushbu-kumari-87090** [comment]
okk i wii fix it.

**Comment by Khushbu-kumari-87090** [comment]
#281 i have added css file  and fix it.

**Review by VidhiBhatt01 — COMMENTED** [review]
closed

**Pull request closed without merging**
