### PR TITLE
Added chrome extension UI (App blocker app)

### PR DESCRIPTION
**Pull request by aaryahjolia**
# Description

Included UI of chrome extension

Fixes:  #740

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

image

### CODE REVIEW

**Comment by DEEPIKA-SUK** [comment]
@aaryahjolia update style_links.json

**Comment by aaryahjolia** [comment]
@DEEPIKA-SUK Please review now

**Comment by aaryahjolia** [comment]
> @aaryahjolia kindly share the resources that you have taken for your reference.

I've taken reference to built manifest.json file which is required to tell chrome that this is an extension from this youtube playlist : 
[https://www.youtube.com/playlist?list=PLC3y8-rFHvwg2-q6Kvw3Tl_4xhxtIaNlY](https://www.youtube.com/playlist?list=PLC3y8-rFHvwg2-q6Kvw3Tl_4xhxtIaNlY)

**Review by DEEPIKA-SUK — APPROVED** [review]

**Comment by DEEPIKA-SUK** [comment]
@aaryahjolia don't mention another pull request here.

**Comment by aaryahjolia** [comment]
> @aaryahjolia don't mention another pull request here.

My bad. But now I'm unable to unlink it. So will my PR won't considered ? Because there's still change requested label.

**Comment by aaryahjolia** [comment]
@arpit456jain Can the level be increased to Level2 as I've built it from scratch by learning how to make extension and also it is a 3 section UI that pop up when we click respective section title.

**Pull request merged**
