### PR TITLE
#533 Wikipedia Clone created

### PR DESCRIPTION
**Pull request by Kumar-laxmi**
# Description

This PR solved the issue to create a new Wikipedia clone, the clone includes the main search page of Wikipedia where the user can search about different things in different languages

Fixes:  #533 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [X] I have made this from my own
- [X] I have taken help from some online resourses 
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
### Screen Shot
image

### Deployment Link
https://kumar-laxmi.github.io/Wikipedia-Clone/

### CODE REVIEW

**Comment by arpit456jain** [comment]
@Kumar-laxmi 
1. did u make it from ur own
2. did u add this in any other project

**Comment by Kumar-laxmi** [comment]
> @Kumar-laxmi
> 
> 1. did u make it from ur own
> 2. did u add this in any other project

This my own project, I worked on this for 3-4 days continuously and till now this isn't there in any project of GSSoC'22

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
This PR is too large. Try to reduce the size and remove all unwanted stuff

**Comment by Kumar-laxmi** [comment]
@VidhiBhatt01 Please check once, I have removed some unwanted libraries

**Review by astha2412 — COMMENTED** [review]
Delete your Portfolio template folder...…Rest is Fine.

**Comment by Kumar-laxmi** [comment]
> Delete your Portfolio template folder...…Rest is Fine.

@astha2412 Portfolio Template Folder isn't my work, it is someone else-work

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Still large, try reducing the number of files to two-digit. It's just a template, no need to add all functionalities.

**Comment by Kumar-laxmi** [comment]
@VidhiBhatt01 Reduced to 41 files

**Review by VidhiBhatt01 — APPROVED** [review]
Cool!

**Comment by arpit456jain** [comment]
@Kumar-laxmi 

https://joserphc.github.io/WikipediaClone/

any clarifications

**Comment by Kumar-laxmi** [comment]
> @Kumar-laxmi
> 
> https://joserphc.github.io/WikipediaClone/
> 
> any clarifications

@arpit456jain Bro ok let me clarify there might be similarities in clones created by me and other people 
The SVG are readily available on wikipedia

**Comment by arpit456jain** [comment]
> > @Kumar-laxmi
> > https://joserphc.github.io/WikipediaClone/
> > any clarifications
> 
> @arpit456jain Bro ok let me clarify there might be similarities in clones created by me and other people The SVG are readily available on wikipedia

@Kumar-laxmi so r u sure this is not plag because if we find it plag in future ur other PRs will also go invalid

**Comment by Kumar-laxmi** [comment]
Yeah bro, like for example: https://commons.wikimedia.org/wiki/File:Wikibooks-logo.svg

**Comment by Kumar-laxmi** [comment]
> > > @Kumar-laxmi
> > > https://joserphc.github.io/WikipediaClone/
> > > any clarifications
> > 
> > 
> > @arpit456jain Bro ok let me clarify there might be similarities in clones created by me and other people The SVG are readily available on wikipedia
> 
> @Kumar-laxmi so r u sure this is not plag because if we find it plag in future ur other PRs will also go invalid

@arpit456jain Yeah bro

**Comment by Kushal997-das** [comment]
@Kumar-laxmi remove the tags as it already present .

https://github.com/khushi-purwar/WebDev-ProjectKart/pull/425

**Comment by arpit456jain** [comment]
@Kumar-laxmi u added this template in multiple repo and i already asked you about it and you lied also...
U know u may be banned from GSSoC'22

Well i will mark all of your PRs invalid until we check them whether they are valid or not .

**Comment by Kumar-laxmi** [comment]
> @Kumar-laxmi u added this template in multiple repo and i already asked you about it and you lied also... U know u may be banned from GSSoC'22
> 
> Well i will mark all of your PRs invalid until we check them whether they are valid or not .

Sorry that I have added to another repo but this is not plagarism and is uniquely my work, but I can assure you that this might not be repeated in future

**Comment by Kumar-laxmi** [comment]
About adding the template in multiple PR I won't repeat in future

**Pull request merged**
