### PR TITLE
Adding the Ui of Discord

### PR DESCRIPTION
**Pull request by soumali28**
# Description

This is the frontend clone of discord using html and css.

Fixes:  #738 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Discord UI Clone - Google Chrome 03-05-2022 20_14_53

### CODE REVIEW

**Comment by DEEPIKA-SUK** [comment]
@soumali28 Make it responsive.
Screenshot (125)

**Comment by soumali28** [comment]
Discord UI Clone - Google Chrome 05-05-2022 09_02_01

It's already responsive.

**Review by DEEPIKA-SUK — APPROVED** [review]

**Comment by DEEPIKA-SUK** [comment]
@soumali28 update style_links.json

**Comment by soumali28** [comment]
@DEEPIKA-SUK its already updated I checked the deployed link on my phone

**Comment by DEEPIKA-SUK** [comment]
> @DEEPIKA-SUK its already updated I checked the deployed link on my phone 

I meant to say that add this project in style_links.json file.

**Comment by soumali28** [comment]
I have made the changes @DEEPIKA-SUK

**Review by DEEPIKA-SUK — APPROVED** [review]

**Comment by DEEPIKA-SUK** [comment]
@soumali28 correct the link in style_links.json file.

**Review by DEEPIKA-SUK — APPROVED** [review]

**Pull request merged**
