### PR TITLE
Added Google Auth Method

### PR DESCRIPTION
**Pull request by Abh1shekSingh**
# Description

Added Google Authentication

Fixes:  #809 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by Abh1shekSingh** [comment]
@arpit456jain  please merge this one also.

**Comment by Abh1shekSingh** [comment]
@DEEPIKA-SUK  Jab mene PR bnai thi, tab toh Merge conflicts nhi show kr raha tha, yeh abb hi kr raha hai, abb mein kya Karu isme?

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Resolve to karna padega. Agar nahi ho raha then make a new PR and close this one

**Comment by Abh1shekSingh** [comment]
Will Closing to make new PR and Resolve Conflicts

**Pull request closed without merging**
