### PR TITLE
PR for netflix clone

### PR DESCRIPTION
**Pull request by Girlwithasmile**
# Description
I hv made another netflix clone template inside page with movies, hover effects. I hv also attached an image for preview.
This is my first ever pr being a beginner so kindly let me know if any mistakes.

Fixes # (issue no.)
#197 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# Explain the Testing instructions

**Test Configuration**:

- Operating system:
- Version:
- Text-editors used:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot 2022-03-02 152312

### CODE REVIEW

**Comment by arpit456jain** [comment]
@Girlwithasmile solve resolve conflicts 

and did u really made this from your own?

**Comment by Girlwithasmile** [comment]
> @Girlwithasmile solve resolve conflicts
> 
> and did u really made this from your own?

Conflicts resolved. If there are any more issues or mistakes pls let me know.
Yes I've made it on my own. It is also available on my github profile.

**Review by VidhiBhatt01 — COMMENTED** [review]
https://codepen.io/cb2307/pen/XYxyeY

**Comment by Girlwithasmile** [comment]
But I had mentioned I coded it from a video...

**Comment by VidhiBhatt01** [comment]
It's the exact same code, you said you referred. Had to add plag label as our main site is getting warnings from google due to plagiarised PRs

**Pull request merged**
