### PR TITLE
Floor Plans Website 

### PR DESCRIPTION
**Pull request by Kamleshseervi**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #850 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
https://deploy-preview-884--cool-front-end-templates.netlify.app/floor%20plan%20website

1. Remove glassmorphic profile card files from this PR.
2. Add this project in style_links.json file

**Review by Kamleshseervi — COMMENTED** [review]
reviewed all file

**Comment by Kamleshseervi** [comment]
done all changes

**Comment by DEEPIKA-SUK** [comment]
> https://deploy-preview-884--cool-front-end-templates.netlify.app/floor%20plan%20website
> 
> 1. Remove glassmorphic profile card files from this PR.
> 2. Add this project in style_links.json file

.

**Comment by Kamleshseervi** [comment]
can i create new pull request because I am not able to delete old commit

**Comment by DEEPIKA-SUK** [comment]
yes do asap.

**Pull request closed without merging**
