### PR TITLE
:memo: updated readme

### LINKED ISSUE #239: move pic of hactoberfest to below devincept and replace it with the logo og GSSoC'22
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [x] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

### PR DESCRIPTION
**Pull request by sarthakk24**
# Description

Updated readme for gssoc'22 moved hacktoberfest 2021 below devincept 

Fixes #239 

## Type of change
Readme updated

# Checklist:

- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Capture
Capture2

### CODE REVIEW

**Comment by sarthakk24** [comment]
Added the mentor's section right below Gssoc title

**Comment by astha2412** [comment]
> Added the mentor's section right below Gssoc title

Add mentor's section after project admin....and push your changes in new branch....don't push your changes directly to master branch.

**Comment by arpit456jain** [comment]
@sarthakk24 
add the section like this below project admin section , if u r not able to do this in this PR do let us know
image

**Comment by sarthakk24** [comment]
updated the readme with mentors section

**Comment by astha2412** [comment]
> updated the readme with mentors section

Plz, don't remove the Project Admin section...Add Mentors section just below the project admin section.

**Comment by sarthakk24** [comment]
added mentors section after the admins section nad pushed it to master branch to prevent opening a whole new pull reques
Capture

**Comment by astha2412** [comment]
> added mentors section after the admins section and pushed it to master branch to prevent opening a whole new pull request Capture

Fine!!

**Comment by astha2412** [comment]
@sarthakk24 add mentors section in other two repos also Amazing-Js and Amazing-CSS

**Comment by sarthakk24** [comment]
I have made the pr request in both the repo's too

**Pull request merged**
