### PR TITLE
Enhance header,body and footer section

### PR DESCRIPTION
**Pull request by Abhishek2408**
# Description

Enhance footer section like design proper navigation bar for website.Added color scheme to website before that is simple and whitish and make changes in card parts of CEO, footer section is looking good now and last this it is complete responsive.

Fixes # (issue no.)

Website looks very basic before changes

## Type of change

# Explain the Testing instructions

**Test Configuration**:

- Operating system: windows
- Version:11
- Text-editors used:vs code

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image
image
image
image
image
image
image
image

### CODE REVIEW

**Comment by Abhishek2408** [comment]
@arpit456jain @VidhiBhatt01 Can u please check and merge this pull request.

**Comment by arpit456jain** [comment]
a

@Abhishek2408

**Comment by Abhishek2408** [comment]
@arpit456jain i have fix this issue. next what i have to do??

**Review by VidhiBhatt01 — COMMENTED** [review]
approved

**Pull request merged**
