### PR TITLE
Starbucks Frontend UI Template 

### LINKED ISSUE #266: Starbucks Frontend Ui Template
High Fidelity UI Design of Starbucks Front Page using HTML , CSS.

A much better version with effective and efficient code.

### PR DESCRIPTION
**Pull request by dexterousb**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #266 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:

- Operating system:
- Version:
- Text-editors used:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Review by VidhiBhatt01 — COMMENTED** [review]
https://github.com/bradtraversy/starbucks-homepage/blob/main/index.html

**Comment by dexterousb** [comment]
pulling another request for the same , I uploaded different file!

**Comment by dexterousb** [comment]
https://naughty-hamilton-904b8d.netlify.app 
- link to the project , that I wanted to pull

**Comment by dexterousb** [comment]
please assign the task again for the same !

**Pull request merged**
