### PR TITLE
Added Google Authentication 

### PR DESCRIPTION
**Pull request by Abh1shekSingh**
# Description

Added Google Authentication MEthod To Register and Log In the user.

Fixes:  #809 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
afterlogin
proof

### CODE REVIEW

**Comment by Abh1shekSingh** [comment]
@VidhiBhatt01 @DEEPIKA-SUK @astha2412 Please review my task

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
https://deploy-preview-814--cool-front-end-templates.netlify.app/login%20form/


Style_links.json

**Review by DEEPIKA-SUK — CHANGES_REQUESTED** [review]
@Abh1shekSingh getting error alert saying unauthorized domain while trying google auth so fix this and resolve merge conflicts.

**Comment by Abh1shekSingh** [comment]
> @Abh1shekSingh getting error alert saying unauthorized domain while trying google auth so fix this and resolve merge conflicts.

Once it will get mergedg, it won't show unauthorised domain.

**Comment by Abh1shekSingh** [comment]
Made A New PR #823  For the same @DEEPIKA-SUK @VidhiBhatt01 @astha2412

**Pull request closed without merging**
