### PR TITLE
Car manufacturing company

### PR DESCRIPTION
**Pull request by srinjoy-26**
# Description

Added a project.
Fixes:  #804 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot 2022-05-25 232132

### CODE REVIEW

**Review by DEEPIKA-SUK — CHANGES_REQUESTED** [review]
@srinjoy-26 correct title also in html file and why other project links changes are also there in style_lnks.json file.

**Comment by srinjoy-26** [comment]
> @srinjoy-26 correct title also in html file and why other project links changes are also there in style_lnks.json file.

Yeah , I did that by mistake, am sorry for that but I have resolved

**Comment by srinjoy-26** [comment]
> > @srinjoy-26 correct title also in html file and why other project links changes are also there in style_lnks.json file.
> 
> Yeah , I did that by mistake, am sorry for that but I have resolved

Title changed @DEEPIKA-SUK

**Review by VidhiBhatt01 — APPROVED** [review]

**Comment by VidhiBhatt01** [comment]
Can you please add a file with the name preview.png which can be used as an image to be displayed on the hosted site?

**Comment by srinjoy-26** [comment]
> Can you please add a file with the name preview.png which can be used as an image to be displayed on the hosted site? 
Yeah sure

**Pull request merged**
