### PR TITLE
NeonScience clone

### PR DESCRIPTION
**Pull request by SupriyaGembali**
This PR fixes the issue Clone this webpage #655.
Kindly review it sir

### CODE REVIEW

**Comment by DEEPIKA-SUK** [comment]
@SupriyaGembali Make it responsive
Screenshot (126)

**Comment by DEEPIKA-SUK** [comment]
@SupriyaGembali complete it in 2 days.

**Comment by DEEPIKA-SUK** [comment]
@SupriyaGembali any updates?

**Comment by arpit456jain** [comment]
@SupriyaGembali i am merging this PR because u had done a great work but make it responsive and make another PR

**Comment by arpit456jain** [comment]
@SupriyaGembali  #734

**Comment by arpit456jain** [comment]
@SupriyaGembali  check #734

**Pull request merged**
