### PR TITLE
#368 Improved Food Website Template

### LINKED ISSUE #368: Improving Food Website Template
**Issue Type:**

- [ ] Documentaion

In this project :
- Some of the key are not working(Contact Us is not smoothly scroll)
- Content is not done in Our Services section
- CSS of hover effect

## **Possible solution**

- Make Contact Us button smooth scrolled .
- Complete the content of Our Services .
- Add hover effect in Contact Us section.

### PR DESCRIPTION
**Pull request by Vanshika7902**
# Description

In this website -
- I changed the services in Our Services section from Food Ordering to Food Ordering , Combo Ordering and Food Delivery and add relevant images and content in it .
- I also add some content in the Home section.
- I add hovering effect in contact us section . 
- I also fixed Contact Us button in the nav-bar , now on clicking it we will move to the Contact Us section . 
 
Fixes #368

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:

- Operating system:
- Version:
- Text-editors used:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

**Before :**

Screenshot (28)

Screenshot (24)

Screenshot (27)

**After :** 

Screenshot (29)

Screenshot (25)

Screenshot (26)

### CODE REVIEW

**Review by VidhiBhatt01 — APPROVED** [review]

**Comment by VidhiBhatt01** [comment]
Good job 👍

**Comment by arpit456jain** [comment]
@Vanshika7902 contact us button is not working rest all is nice

**Comment by Vanshika7902** [comment]
I fixed the navbar issue , kindly review it .

**Review by astha2412 — CHANGES_REQUESTED** [review]
@Vanshika7902 after clicking on contact us....there is no option to go back with your navbar....Can u plz fix it?? or U want to get your PR merged? Let us know

**Pull request merged**
