### PR TITLE
#532 Solved

### PR DESCRIPTION
**Pull request by juberiya1ajaz**
# Description

I had improved the responsiveness of this templaet

Fixes:  #532

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image

### CODE REVIEW

**Comment by arpit456jain** [comment]
@juberiya1ajaz

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
https://deploy-preview-631--cool-front-end-templates.netlify.app/rural%20art%20template/


1. Remove Food Ordering files.
2. Responsiveness is still not fixed.

image

**Comment by VidhiBhatt01** [comment]
Resolve merge conflicts too

**Comment by VidhiBhatt01** [comment]
@juberiya1ajaz

**Comment by Anirban-1490** [comment]
@VidhiBhatt01 well i have already fixed this issue and PR was merged too #605

**Pull request closed without merging**
