### PR TITLE
Added a new Frontend Template

### PR DESCRIPTION
**Pull request by RajAdwaita**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

This is a cool FrontEnd Website that I coded using react and it's various features
To begin working on this website or to view in localhost, firstly, clone the repository from GitHub, then,
run npm install
after the node modules are installed,
-> npm start 
and the website will run on your localhost

Fixes # (issue no.)

437
## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Explain the Testing instructions
First run npm install 
Then npm start (to run) in localhost
**Test Configuration**:

- Operating system: windows/linux/macOS
- Version: Any
- Text-editors used: VS CODE

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot 2022-03-17 172020
Screenshot 2022-03-17 172104
Screenshot 2022-03-17 172133
Screenshot 2022-03-17 172154
Screenshot 2022-03-17 172246

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Link the issue properly in PR description and remove all unnecessary files.

**Review by VidhiBhatt01 — COMMENTED** [review]
Also, HTML and CSS is not getting applied properly, kindly look into that and fix it.

https://deploy-preview-453--cool-front-end-templates.netlify.app/shoestore/public/

**Comment by RajAdwaita** [comment]
I think that this is not getting deployed properly as I made this using react, and I have already deployed it using npm build 

https://gssocstore.netlify.app/

**Comment by RajAdwaita** [comment]
> Link the issue properly in PR description.

sure maam

**Comment by VidhiBhatt01** [comment]
We are only accepting projects based on pure JS rn, hence closing it. Keep an eye on the announcement channel, we will post there if we start accepting React projects. You can raise a PR at that time : )

**Pull request closed without merging**
