### PR TITLE
Nestle Nutrition Clone

### PR DESCRIPTION
**Pull request by DragonUncaged**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #763 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

## [Taken From](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.fda.gov%2Ffood%2Ffood-labeling-nutrition%2Fnutrition-facts-label-images-download&psig=AOvVaw3ucB_-EQfSTGr0g5nHruHp&ust=1651997541441000&source=images&cd=vfe&ved=0CA0QjhxqFwoTCKiKssf4zPcCFQAAAAAdAAAAABAU)

### CODE REVIEW

**Review by DEEPIKA-SUK — APPROVED** [review]

**Comment by DEEPIKA-SUK** [comment]
@DragonUncaged update the style_links.json with correct link.

**Comment by DragonUncaged** [comment]
> @DragonUncaged update the style_links.json with correct link.

Done !!

**Review by DEEPIKA-SUK — APPROVED** [review]

**Comment by arpit456jain** [comment]
@DragonUncaged  font is very big make it user friendly

image

**Comment by DragonUncaged** [comment]
> @DragonUncaged font is very big make it user friendly
> 
> image

this is just the design.
If i will make the font small there will be white space which will bot look good.

**Comment by DEEPIKA-SUK** [comment]
https://deploy-preview-772--cool-front-end-templates.netlify.app/nestle%20nutrition%20clone/

**Pull request merged**
