### PR TITLE
Added Haldiram's Website Clone

### PR DESCRIPTION
**Pull request by SupriyaGembali**
This is the PR for the issue Haldiram's Website Clone #671. Please review this and kindly make a further move 😁.
Thank you Sir

### CODE REVIEW

**Comment by arpit456jain** [comment]
@SupriyaGembali merge conflicts

**Comment by SupriyaGembali** [comment]
@arpit456jain Conflicts have been resolved, Please review my PR

**Comment by arpit456jain** [comment]
@SupriyaGembali  
https://deploy-preview-672--cool-front-end-templates.netlify.app/

u r changing the index file of home page
and u r adding  a lots of file 

remove unnecessary files and make new PR

**Review by VidhiBhatt01 — COMMENTED** [review]
invalid,closed

**Pull request closed without merging**
