### PR TITLE
Added Blogger's template

### PR DESCRIPTION
**Pull request by Girlwithasmile**
# Description
 I've created a Blogger's template for the website. If there are any changes pls let me know.

Fixes # (issue no.)
#198 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# Explain the Testing instructions

**Test Configuration**:

- Operating system:
- Version:
- Text-editors used: Vs Code

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
bloggerpreview
websitfooterpreview

### CODE REVIEW

**Comment by VidhiBhatt01** [comment]
@Girlwithasmile add ticks in the PR template

**Comment by VidhiBhatt01** [comment]
Also, @arpit456jain @astha2412 are you able to see the deployed website?

**Comment by arpit456jain** [comment]
https://deploy-preview-324--cool-front-end-templates.netlify.app/bloggers%20template/my%20desert%20safari

**Review by VidhiBhatt01 — COMMENTED** [review]
approved

**Pull request merged**
