### PR TITLE
Navbar buttons now point to the correct section of the page

### PR DESCRIPTION
**Pull request by ez-sherlock**
# Description

Fixed the issue where the navbar buttons were static. Now on clicking them they navigate to their corresponding sections of the pages.

Fixes:  #555 

## Type of change

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x ] I have made this from my own
- [ ] I have taken help from some online resourses 
- [ ] I have made corresponding changes to the documentation
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
https://cool-front-end-templates.netlify.app/online%20grocery-%20store/

### CODE REVIEW

**Comment by arpit456jain** [comment]
@ez-sherlock u changes the id of div that's why its not getting its correct css 

https://deploy-preview-567--cool-front-end-templates.netlify.app/online%20grocery-%20store/#services

make it correct

**Comment by ez-sherlock** [comment]
Made the changes please have a look

**Review by VidhiBhatt01 — APPROVED** [review]

**Comment by arpit456jain** [comment]
image

@ez-sherlock our services should be on top 
@VidhiBhatt01 is it same in ur side ?

**Comment by VidhiBhatt01** [comment]
it follows about us and then services ig.

**Comment by ez-sherlock** [comment]
I think everything is fine. If there're any issues, do let me know then ;)

**Comment by arpit456jain** [comment]
@ez-sherlock i suggest u to make a new PR and make changes again carefully

**Pull request closed without merging**
