### PR TITLE
New Interface Of the Chinese Restaraunt Project

### PR DESCRIPTION
**Pull request by Abh1shekSingh**
# Description

New Interface

Fixes:  #713 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

BEFORE: 
before1
before2
before3

AFTER:
after1
after2
after4

### CODE REVIEW

**Comment by Abh1shekSingh** [comment]
@VidhiBhatt01 @astha2412 @DEEPALI-SUK Please review

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Remove extra files and fix this
image

**Comment by VidhiBhatt01** [comment]
https://deploy-preview-761--cool-front-end-templates.netlify.app/chinese%20restaurant/

**Comment by Abh1shekSingh** [comment]
@VidhiBhatt01 I have made  the changes, once you will merge it it wont show any responsiveness breaking issue. and then avatar, is shifted to right side, out of screen because I did that personally, its not by mistake. Once you will merge and see on original site, it wont create any issue

design
okay

**Comment by Abh1shekSingh** [comment]
@VidhiBhatt01 And yrr I dont know, extra files kaise sath mein aa jaati hai, pata nhi kya probelm hai yeh. Mereko yeh cheez theek nhi aati krni

**Comment by Abh1shekSingh** [comment]
@VidhiBhatt01 @astha2412 @DEEPALI-SUK Please Merge the PR. I have add the chnages, the site wont break once it get deploy. Because I have added Overflow value to hidde,. Alos that image is out of screen, because i did that personally to add some design

**Comment by arpit456jain** [comment]
@Abh1shekSingh its not responsive and instead of changing previous one add this one as a new template don't remove the previous one  
image

**Comment by arpit456jain** [comment]
suggestion :  checkout to master branch copy the restaurant template somewhere
checkout to Chinese branch  then rename this folder and cut paste that folder in reop

**Comment by Abh1shekSingh** [comment]
sample1
sample2
@arpit456jain Made it responsive now. Please Do not check responsiveness using console tool.

**Comment by arpit456jain** [comment]
@Abh1shekSingh brother ur  PR contains files from previous commits
update ur master branch then make a new branch and add the project and make PR

**Comment by Abh1shekSingh** [comment]
Brother pata nhi kaise aa jaati hai, mein toh har baar, fetch and pull krke
hi new changes krta hu

**Pull request closed without merging**
