### PR TITLE
Added Adobe website clone

### PR DESCRIPTION
**Pull request by eswarbhageerath**
This is the PR of the issue Adobe website clone #692. Please review it

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Make it responsive for all screen sizes.
image


Add it in style_links.json, Add references in a readme file

**Comment by VidhiBhatt01** [comment]
https://deploy-preview-732--cool-front-end-templates.netlify.app/adobe%20website%20clone/

**Comment by DEEPIKA-SUK** [comment]
@eswarbhageerath do the changes within 2-3 days.

**Comment by DEEPIKA-SUK** [comment]
@eswarbhageerath any updates?

**Comment by arpit456jain** [comment]
its not responsive make it responsive  and make PR again

**Pull request closed without merging**
