### PR TITLE
Haldirams Website Clone

### PR DESCRIPTION
**Pull request by SupriyaGembali**
This is the PR of the issue Haldiram's Website Clone #671.
Kindly review it sir 😁

### CODE REVIEW

**Comment by VidhiBhatt01** [comment]
https://deploy-preview-706--cool-front-end-templates.netlify.app/haldiram's%20website%20clone/

**Comment by VidhiBhatt01** [comment]
I am a female first of all🙃

Secondly, your code is 6k lines plus. It's time consuming so abhi fix nai karna to chalega. Bas next time se make sure you make separate files.

**Comment by SupriyaGembali** [comment]
@VidhiBhatt01 Sure mam

**Comment by SupriyaGembali** [comment]
@VidhiBhatt01 I have fixed the responsiveness as much as I can ,  Removed Horizontal Scrolling, Made the crowded footer section a neat and spacious by text edits,  Added this project in style_links.json file.. Kindly review

**Comment by VidhiBhatt01** [comment]
image
 The issue still prevails
 
image

Rather than reducing size, you can change alignment style to vertical here ig
image

**Comment by DEEPIKA-SUK** [comment]
@SupriyaGembali do the changes by tomorrow.

**Comment by DEEPIKA-SUK** [comment]
@SupriyaGembali are you working on this PR or not?? Make the changes by tonight otherwise I will close this PR.

**Pull request closed without merging**
