### PR TITLE
Added WhatsApp

### PR DESCRIPTION
**Pull request by Avik-creator**
I worked on issue #247. I would like to close this issue and make my contribution. I am Avik Mukherjee a GSSOC participant.

### CODE REVIEW

**Comment by VidhiBhatt01** [comment]
LGTM

**Comment by Avik-creator** [comment]
Can I know what is LGTM?

**Comment by VidhiBhatt01** [comment]
Looks Good to me

**Review by VidhiBhatt01 — COMMENTED** [review]
https://github.com/arpit456jain/Cool-Front-End-Templates/pull/246

**Comment by VidhiBhatt01** [comment]
https://deploy-preview-273--cool-front-end-templates.netlify.app/whatsapp/

**Pull request merged**
