### PR TITLE
added new project:Amazon-Clone

### PR DESCRIPTION
**Pull request by kunalahuja06**
# Description

Added new project: Amazon-Clone

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Explain the Testing instructions

**Test Configuration**:

- Operating system: Windows 
- Version: 10
- Text-editors used: VS Code

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by arpit456jain** [comment]
@kunalahuja06 did u add this project in any other repo ?

**Comment by kunalahuja06** [comment]
@kunalahuja06 No, just this repo. In my previous pull request I tried to clone the project in this repo but that didn't work.

**Review by VidhiBhatt01 — COMMENTED** [review]
@kunalahuja06 link the issue number in PR description

**Comment by kunalahuja06** [comment]
@VidhiBhatt01 #381

**Comment by arpit456jain** [comment]
> @VidhiBhatt01 #381

this is the PR link 

whats ur issue link

**Pull request merged**
