### PR TITLE
Readme bug fix resolves issue number #867

### PR DESCRIPTION
**Pull request by itzwow**
# Description

Updates and fixed the typo in Readme.md

Fixes:  #867 

## Type of change

- [x ] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x ] I have made this from my own
- [x ] I have performed a self-review of my own code
- [x ] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
fix

### CODE REVIEW

**Review by DEEPIKA-SUK — CHANGES_REQUESTED** [review]
@itzwow why there are 13 changed files? Only readme file should be changed. Fix this.

**Comment by itzwow** [comment]
> @itzwow why there are 13 changed files? Only readme file should be changed. Fix this.

@DEEPIKA-SUK  actually the first commit is from some different branch and was commited which solves a issue number 866.
Although I have created a new seperate branch for this I don't know how it was also commited.

**Comment by DEEPIKA-SUK** [comment]
> > @itzwow why there are 13 changed files? Only readme file should be changed. Fix this.
> 
> @DEEPIKA-SUK actually the first commit is from some different branch and was commited which solves a issue number 866. Although I have created a new seperate branch for this I don't know how it was also commited.

@itzwow clone the original repo once again and then create new branch.

**Comment by itzwow** [comment]
Kindly delete this Pull request I have made a fresh pull request

**Pull request closed without merging**
