### PR TITLE
Responsive Website Template for a Restaurant. #201

### PR DESCRIPTION
**Pull request by CoderSahil128**
I am a contributor from GSSoC - 22. I have created a Responsive Restaurant Website Template with amazing effects . So kindly Review and merge my PR.

Fixes # 201

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
WhatsApp Image 2022-03-02 at 10 25 04 PM
WhatsApp Image 2022-03-02 at 10 24 34 PM
WhatsApp Image 2022-03-02 at 10 24 09 PM
WhatsApp Image 2022-03-02 at 6 14 28 PM
WhatsApp Image 2022-03-02 at 6 14 01 PM
WhatsApp Image 2022-03-02 at 6 13 15 PM
WhatsApp Image 2022-03-02 at 6 12 32 PM

### CODE REVIEW

**Comment by astha2412** [comment]
Looks good! But your logo and the magnifying glass are overlapping ...just make it correct only... the rest is ok!

**Comment by CoderSahil128** [comment]
> Looks good! But your logo and the magnifying glass are overlapping ...just make it correct only... the rest is ok!

Ol.. I'll do it soon.. Thnx for the suggestion 👍

**Comment by CoderSahil128** [comment]
@VidhiBhatt01 could u please send me the screen shot of the issue

**Comment by CoderSahil128** [comment]
> @CoderSahil128 In the first 6 screenshots you attached, the magnifying glass on navbar is not sized properly also the search box is bigger in size. Just align them properly with CSS

@VidhiBhatt01 I've Updated the file .Now kindly plz review it and merge it.

**Review by VidhiBhatt01 — COMMENTED** [review]
https://deploy-preview-278--cool-front-end-templates.netlify.app/restaurant_template/food

**Pull request merged**
