### PR TITLE
added a book website template under issue #497

### PR DESCRIPTION
**Pull request by Nitya-S27**
# Description

I have added a books website made using bootstrap.

Fixes:  #497 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resources 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
image

Change the color so that it is visible properly

**Comment by Nitya-S27** [comment]
> @Nitya-S27

Yes, I have made the required changes.

**Review by VidhiBhatt01 — APPROVED** [review]
https://deploy-preview-513--cool-front-end-templates.netlify.app/books_website_template/

**Comment by VidhiBhatt01** [comment]
good job! I hope you have made this on your own and not copied from anywhere : )

**Comment by VidhiBhatt01** [comment]
Wait, the merge conflicts needs to be resolved. Fix it please

**Comment by Nitya-S27** [comment]
> good job! I hope you have made this on your own and not copied from anywhere : )

Yes I have made it on my own.

**Comment by Nitya-S27** [comment]
> Wait, the merge conflicts needs to be resolved. Fix it please

Okay

**Comment by Nitya-S27** [comment]
> Wait, the merge conflicts needs to be resolved. Fix it please

The merge conflict has been resolved.

**Review by VidhiBhatt01 — APPROVED** [review]

**Pull request merged**
