### PR TITLE
New Interface For Chinese Restaurant Website

### PR DESCRIPTION
**Pull request by Abh1shekSingh**
# Description

Chinese Restaurant Website Interface

Fixes:  #793 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

AFTER: 

sample1

### CODE REVIEW

**Comment by DEEPIKA-SUK** [comment]
https://deploy-preview-794--cool-front-end-templates.netlify.app/chinese%20restaurant/

**Review by DEEPIKA-SUK — CHANGES_REQUESTED** [review]
@Abh1shekSingh 
1.  Make this button Responsive.
Screenshot 2022-05-11 104327
2.  The color of these texts is changing to white on hover so correct this.
Screenshot 2022-05-11 104340
Screenshot 2022-05-11 104409
3.  Fix this
Screenshot 2022-05-11 104611
4. Icon is not visible
Screenshot 2022-05-11 104643

**Review by DEEPIKA-SUK — COMMENTED** [review]
@Abh1shekSingh List the resources from where you have taken the reference.

**Comment by Abh1shekSingh** [comment]
> @Abh1shekSingh List the resources from where you have taken the reference.

I my self created this design. Didnt take any reference. This project was already in your repo. I just gave it a new interface

**Comment by Abh1shekSingh** [comment]
@VidhiBhatt01 @astha2412 @DEEPIKA-SUK Done the Required changes u asked for. @arpit456jain Please Review and merge if possible

**Review by DEEPIKA-SUK — APPROVED** [review]

**Pull request merged**
