### PR TITLE
Added product landing page

### PR DESCRIPTION
**Pull request by Sreemoyee26**
# Description

Added an Product Landing Page Template

Issue #369  

## Added new template

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Screenshot

Screenshot (670)

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
You need to make it reponsive

image

Also, increase the spacing between these buttons

image

**Comment by Sreemoyee26** [comment]
I have updated the changes as requested. Please check @VidhiBhatt01.

**Comment by VidhiBhatt01** [comment]
https://deploy-preview-449--cool-front-end-templates.netlify.app/productslandingpage/landing_page

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Majorly it's fixed but don't you think these items must be equally spaced and aligned in the center?

image


@arpit456jain what are your views?

**Pull request merged**
