### PR TITLE
Improve the Footer of Chines  Restaurant

### PR DESCRIPTION
**Pull request by AsmaIbrahimButt**
# Description
Enhance the footer section of Chines Restaurant.

Fixes:  #658

## Type of change
Improvement
improve

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have made this from my own
- [ ] I have taken help from some online resourses 
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by AsmaIbrahimButt** [comment]
@arpit456jain Would appreciate to have a look on this pull request.Thanks:)

**Comment by arpit456jain** [comment]
@AsmaIbrahimButt merge conflicts

**Comment by AsmaIbrahimButt** [comment]
@arpit456jain I resolved.Kindly review it.Thanks:)

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
image

The responsiveness of the site is distorted due to the changes. Fix it

**Comment by VidhiBhatt01** [comment]
https://deploy-preview-676--cool-front-end-templates.netlify.app/chinese%20restaurant/

**Comment by astha2412** [comment]
@AsmaIbrahimButt ??? Updates

**Review by astha2412 — APPROVED** [review]

**Comment by AsmaIbrahimButt** [comment]
@astha2412 When i improve the footer section of chines restaurant the changes on my local seems perfect .Do I have to fix the all issues that occur now?

**Comment by AsmaIbrahimButt** [comment]
@astha2412 When i improve the footer section of chines restaurant the changes on my local seems perfect .Do I have to fix the all issues that occur now?

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Tbh, the site was fully responsive earlier. SO yes, you need to fix it. If you don't want to do, let us know we will create an issue for others

**Comment by AsmaIbrahimButt** [comment]
@VidhiBhatt01 I would like to fix it properly.Thanks:)

**Comment by VidhiBhatt01** [comment]
Awesome 🙌

**Comment by arpit456jain** [comment]
@AsmaIbrahimButt make a new PR when ready

**Comment by AsmaIbrahimButt** [comment]
@arpit456jain ok

**Pull request closed without merging**
