### PR TITLE
changed UI of the service section and added bottom navbar.

### PR DESCRIPTION
**Pull request by myhacktech**
# Description
changed UI of the service section and added bottom navbar, also introduced shadow to the boxes.

Fixes:  #(issue no.)

#594 
## Type of change

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x ] I have made this from my own
Screenshot (289)
Screenshot (288)

- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code

- [ x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by myhacktech** [comment]
@astha2412 @VidhiBhatt01 please review this PR

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
https://deploy-preview-637--cool-front-end-templates.netlify.app/simple%20portfolio%20template/

1. The alignment is not proper. Saare logos upar niche hai. It must be in the same line.
2. I think pehle vala bottom navbar/footer was better. Try enhancing the one you made

**Comment by myhacktech** [comment]
@VidhiBhatt01 @astha2412 please review this..

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
better but just please give a different color to the footer

**Review by arpit456jain — APPROVED** [review]

**Pull request merged**
