### PR TITLE
Added URL Landing Page

### PR DESCRIPTION
**Pull request by Abh1shekSingh**
# Description

URL Shortening Landing Page. I have made a landing Page concept of a URL Shortner Project

Fixes:  #701 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
url

### CODE REVIEW

**Review by VidhiBhatt01 — COMMENTED** [review]
I have seen the exact same project in one of our repos.

**Comment by Abh1shekSingh** [comment]
> I have seen the exact same project in one of our repos.

Arey mene btaya toh tha. Ki Frontend mentors krke website hoti hai, waha Challenges hote hai, bhut se Log chellenges solve krte hai waha pe.

**Comment by VidhiBhatt01** [comment]
Haan, but we already have this project included

**Comment by arpit456jain** [comment]
@Abh1shekSingh u can add these kinds of template but before  that take a look on all projects it should not be present in repo

**Comment by Abh1shekSingh** [comment]
SURE SIR G.

**Pull request closed without merging**
