### PR TITLE
added gym website template

### PR DESCRIPTION
**Pull request by nouraan-ahmed**
# Description

I have created An interactive gym website using HTML , CSS and javascript

Fixes:  #682

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
https://nouraan-ahmed.github.io/Fitness-Time/

Screenshot from 2022-04-23 22-00-22
Screenshot from 2022-04-23 22-00-38
Screenshot from 2022-04-23 22-00-47
Screenshot from 2022-04-23 22-00-57
Screenshot from 2022-04-23 22-01-07
Screenshot from 2022-04-23 22-01-11

### CODE REVIEW

**Comment by arpit456jain** [comment]
@nouraan-ahmed how did u make ir

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
https://deploy-preview-683--cool-front-end-templates.netlify.app/gym%20website/

Make it fully responsive

**Comment by VidhiBhatt01** [comment]
image


Also, improve Navbar UI and add the project in style_links.json

**Comment by VidhiBhatt01** [comment]
image

**Review by astha2412 — CHANGES_REQUESTED** [review]
@nouraan-ahmed updates???

**Comment by nouraan-ahmed** [comment]
@astha2412 Done

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Still not fully responsive. Also remove horizontal scrolling

image

**Comment by yash-25log** [comment]
https://github.com/surajm-333/Ace-The-FrontEnd/pull/410
Not allowed to add the same project in multiple repos

**Comment by VidhiBhatt01** [comment]
Yes, you cannot add same project in 2 repos

**Pull request closed without merging**
