### PR TITLE
Added a Coffee Website 

### PR DESCRIPTION
**Pull request by harshraj29**
# Description

Built a Coffee website template for GSSOC'22

Fixes:  #711 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
https://deploy-preview-767--cool-front-end-templates.netlify.app/coffee%20website/

Add the project in style_links.json file

**Comment by DEEPIKA-SUK** [comment]
@harshraj29 do by tonight otherwise I will close this PR.

**Review by harshraj29 — COMMENTED** [review]
i have updated the style_link.json file please approve my changes

**Comment by arpit456jain** [comment]
@harshraj29  navbar toggle is not working in mobile view

**Comment by harshraj29** [comment]
> @harshraj29 

Will fix it by the end of today

**Review by harshraj29 — COMMENTED** [review]
i have fix the nav bar Kindly look and verify the same

**Pull request merged**
