### PR TITLE
personal-portfolio-website#844 added

### PR DESCRIPTION
**Pull request by priyanshi1282**
# Description

Added a personal portfolio website which is made using html and css, no framework is used.
The website is developed responsive.

Fixes:  #844 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
home
about
services
contact

### please consider this under GSSoC'22 contribution.

### CODE REVIEW

**Review by DEEPIKA-SUK — CHANGES_REQUESTED** [review]
@priyanshi1282 remove empty script.js file, add your project in style_links.json file

**Comment by priyanshi1282** [comment]
> @priyanshi1282 remove empty script.js file, add your project in style_links.json file

script file is removed and project is already added in style_links.json file.

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
https://deploy-preview-860--cool-front-end-templates.netlify.app/personal-portfolio-website/index.html

Why is the index.html in the images folder!?

**Comment by priyanshi1282** [comment]
> https://deploy-preview-860--cool-front-end-templates.netlify.app/personal-portfolio-website/index.html
> 
> Why is the index.html in the images folder!?

index.html is not in image folder 😅.
see this screenshot-
Screenshot (97)

**Review by DEEPIKA-SUK — APPROVED** [review]

**Pull request merged**
