### PR TITLE
Template for Cake Shop Website

### PR DESCRIPTION
**Pull request by coolblizzarts**
This PR contains the changes that were asked to be made previously.

# Description

This is a website template for a cake shop. It consists of the cake menu, cake picture gallery and a customer review page. The changes that were requested previously have been made.

Fixes:  #802)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by coolblizzarts** [comment]
I have made the changes to the Cake Shop Website that were requested. Kindly go through it and provide feedback.

**Review by VidhiBhatt01 — APPROVED** [review]
Not fully responsive but approving as we are at the end of contribution period.
image

**Comment by VidhiBhatt01** [comment]
https://deploy-preview-887--cool-front-end-templates.netlify.app/cakeshopwebsite/

@arpit456jain please verify once again as there are many changes in style_links.json before merging

**Comment by coolblizzarts** [comment]
> Not fully responsive but approving as we are at the end of contribution period. image

Okay, thank you. Sorry about the error. Will I be getting a score assigned for this PR then?

**Comment by coolblizzarts** [comment]
Hello, any updates? Do I need to make any more changes or will this PR get merged?

**Review by DEEPIKA-SUK — CHANGES_REQUESTED** [review]
@coolblizzarts resolve merge conflicts asap.

**Comment by coolblizzarts** [comment]
> @coolblizzarts resolve merge conflicts asap.

Done. Resolved the merge conflicts.

**Comment by DEEPIKA-SUK** [comment]
@arpit456jain

**Review by DEEPIKA-SUK — APPROVED** [review]

**Pull request merged**
