### PR TITLE
Travel Website - Travellrr.

### PR DESCRIPTION
**Pull request by kunal-kataria**
# Description

This is a Travel Website template. It contains home page, About us page, Destination page and Login/Register page. I made this website using HTML, CSS and JavaScript.

Fixes:  #818

## Type of change

- [x] Responsiveness feature fixed
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
image
Make it fully responsive. Also are you sure you made it on your own?

**Comment by VidhiBhatt01** [comment]
https://deploy-preview-877--cool-front-end-templates.netlify.app/travel%20website/index.html

**Comment by kunal-kataria** [comment]
Yes, I have made this on my own. I have this website with some beginner backend services on my github. I have resolved the responsiveness issue.

**Comment by kunal-kataria** [comment]
@DEEPIKA-SUK I have made changes in header and destination row also.

**Review by DEEPIKA-SUK — APPROVED** [review]
Nice work!

**Review by VidhiBhatt01 — APPROVED** [review]

**Pull request merged**
