### PR TITLE
Add college fest template 

### PR DESCRIPTION
**Pull request by yashikhare**
# Description

This is  a college fest webpage template. It contains About us and events section.
I have used html and css for making this college fest template.

Fixes # (375)

## Type of change
- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

# Explain the Testing instructions

**Test Configuration**:

- Operating system: windows
- Text-editors used: vs code 

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] My changes generate no new warnings

# VIDEO
https://user-images.githubusercontent.com/72096769/157244494-9ac1db1d-b755-4c35-b7a3-4d0b10948d9e.mp4

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
I can't find the project on the deployed link. Also link the issue properly in PR description

**Comment by arpit456jain** [comment]
https://deploy-preview-389--cool-front-end-templates.netlify.app/college-fest/index.html

@yashikhare its not at responsive

**Comment by VidhiBhatt01** [comment]
@yashikhare link the issue properly in description and try to make it  a little responsive

**Comment by yashikhare** [comment]
ok

**Comment by arpit456jain** [comment]
@yashikhare make a new PR when its ready

**Comment by yashikhare** [comment]
ok

**Pull request closed without merging**
