### PR TITLE
NVIDIA_Clone

### PR DESCRIPTION
**Pull request by Sukriti-m**
# Description

This is a NVIDIA Clone made using Javascript,CSS,HTML5

Fixes:  #699 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS

nd

nd1

nd2

# DEPLOYMENT LINK: https://subtle-palmier-919a35.netlify.app/

@arpit456jain  @VidhiBhatt01 @DEEPIKA-SUK  Please review this PR.

### CODE REVIEW

**Comment by DEEPIKA-SUK** [comment]
@Sukriti-m It is still not responsive for small window size.
Screenshot 2022-05-09 083321
Screenshot 2022-05-09 083214
Screenshot 2022-05-09 083239
Screenshot 2022-05-09 083257

**Comment by DEEPIKA-SUK** [comment]
@Sukriti-m any updates?

**Comment by Sukriti-m** [comment]
I will try to make the changes by tonight.

**Comment by DEEPIKA-SUK** [comment]
@Sukriti-m do it by tomorrow afternoon otherwise we will close this PR.

**Comment by Sukriti-m** [comment]
> @Sukriti-m do it by tomorrow afternoon otherwise we will close this PR

I apologise that I won't be able to do it as I am busy with my college exams. You can close this PR.

**Pull request closed without merging**
