### PR TITLE
added two templates under issue #357 vegan-store and read-me

### PR DESCRIPTION
**Pull request by Nitya-S27**
# Description

I have added two more cool frontend templates one for vegan store and other for a book website named Read-Me.

Fixes # (issue no. #357 )

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:

- Operating system: Windows
- Version: 11
- Text-editors used: Visual Studio Code

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

Screenshot (383)

Screenshot (384)

### CODE REVIEW

**Review by VidhiBhatt01 — COMMENTED** [review]
LGTM

**Comment by arpit456jain** [comment]
merge conflicts @Nitya-S27

**Comment by arpit456jain** [comment]
https://mobirise.com/extensions/organicamp/demo3.html

**Comment by arpit456jain** [comment]
https://vegan-store-web.netlify.app/

**Comment by arpit456jain** [comment]
@Nitya-S27 did  u copy it ?

**Comment by Nitya-S27** [comment]
> @Nitya-S27 did u copy it ?

No I made the vegan store landing page under a course.

**Comment by arpit456jain** [comment]
> > @Nitya-S27 did u copy it ?
> 
> Actually I made the vegan store landing page under a course. This might have caused plagiarism. I'm sorry and didn't realise.


make changes in that template then only we can accept that
plus always create seperate PRs for 2 templates

**Pull request closed without merging**
