### PR TITLE
Yashashviarora patch 1

### PR DESCRIPTION
**Pull request by Yashashviarora**
In this i change font size of navigation bar and color of that navigation bar #826 and #issue-Yashashviarora-patch-1

### CODE REVIEW

**Comment by Yashashviarora** [comment]
@VidhiBhatt01  Now Is this website working good or not

**Review by DEEPIKA-SUK — CHANGES_REQUESTED** [review]
@Yashashviarora add issue number in the description properly, add screenshot or video as we are not able to view website, resolve merge conflicts. Do asap

**Comment by DEEPIKA-SUK** [comment]
@Yashashviarora update style_links.json file with correct url. There is no index.html file in your folder, so remove that name and instead add anchortag.html.

**Comment by DEEPIKA-SUK** [comment]
https://deploy-preview-889--cool-front-end-templates.netlify.app/mobile_template/anchortag

**Comment by DEEPIKA-SUK** [comment]
@Yashashviarora rest is good just fix style_links.json file and remove merge conflicts.

**Review by VidhiBhatt01 — COMMENTED** [review]
Hey Yashvi, the contribution period ends soon. I see you are a first-time contributor and hence facing issues. So I would suggest that take help from someone on the server and fix this ASAP. If you don't get any reply, you are free to DM me :)

**Review by DEEPIKA-SUK — APPROVED** [review]

**Pull request merged**
