### PR TITLE
Kinetic Preloader added

### LINKED ISSUE #323: Add a Preloader
## Issue Type:

- [x] Feature Request

I wanted to add a preloader made with CSS only.

## **Screenshots**
Screenshot 2022-03-04 at 7 26 26 PM

Both the triangles rotate in a clockwise manner.

### PR DESCRIPTION
**Pull request by varisha-025**
# Description

Fixes #323 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

No testing required.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by VidhiBhatt01** [comment]
This looks cool!!

**Comment by varisha-025** [comment]
@VidhiBhatt01  Please merge the PR. I have already raised the PR

**Comment by VidhiBhatt01** [comment]
PA will merge it soon

**Comment by VidhiBhatt01** [comment]
I can only review it.

**Comment by varisha-025** [comment]
Okay mam

**Comment by arpit456jain** [comment]
@varisha-025 template is cool but please make this PR in amazing css effects

**Pull request closed without merging**
