### PR TITLE
Added a Restaurant template

### PR DESCRIPTION
**Pull request by kheya19**
# Description
Added a restaurant template using bootstrap.

Fixes # (issue no.262)

## Type of change
Made a restaurant template using bootstrap.

# Explain the Testing instructions

**Test Configuration**:

- Operating system: Windows 10
- Version:
- Text-editors used: VS Code

# Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
download

### CODE REVIEW

**Comment by VidhiBhatt01** [comment]
@kheya19 link the issue in description properly

**Comment by kheya19** [comment]
> @kheya19 link the issue in description properly

Ok

**Comment by kheya19** [comment]
can you please check it and tell me is it okay or not ??

**Comment by VidhiBhatt01** [comment]
Are you sure you made it on your own? 👀

**Review by VidhiBhatt01 — APPROVED** [review]

**Comment by kheya19** [comment]
> Are you sure you made it on your own? 👀

Yes but I have taken the idea from bootstrap template.

**Comment by arpit456jain** [comment]
great work @kheya19 

there is some work in responsiveness if want to work on it create a issue for it start working on it

**Comment by arpit456jain** [comment]
#262

**Comment by kheya19** [comment]
> great work @kheya19 
> 
> there is some work in responsiveness if want to work on it create a issue for it start working on it

Ok sure

**Pull request merged**
