### PR TITLE
Made website responsive and introduced transition in dialing icon phone number 

### PR DESCRIPTION
**Pull request by myhacktech**
# Description
Earlier website was not not responsive, which i have made it completely responsive and  dialing icon which was static, i brought transition feature to that ,and the body background color is changed.
Fixes:  #(issue no.)

#460

## Type of change

website is now responsive,and a transition feature is introduced to dialing icon.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ x] I have made this from my own

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code

- [x ] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot (257)
Screenshot (256)

### CODE REVIEW

**Comment by myhacktech** [comment]
@arpit456jain sir please review the pull request

**Comment by DEEPIKA-SUK** [comment]
@myhacktech Please link the issue in the description properly.

**Comment by myhacktech** [comment]
> 

i did not 

> Fix these things:
> 
> 1. Book now button is overlapping.
>    Screenshot (90)
> 2. This is not entirely responsive as here we need to scroll horizontally.
>    Screenshot (91)
>    Screenshot (92)

i got 1st issue, but i am not facing  the 2nd issue in my system, could you please help in understanding

**Review by astha2412 — COMMENTED** [review]
https://deploy-preview-486--cool-front-end-templates.netlify.app/hotel%20website/

**Comment by astha2412** [comment]
Screenshot (419)
I m not facing any issue regarding horizontal movement. Can u all plz confirm again @DEEPIKA-SUK @DEEPALI-SUK @VidhiBhatt01. 
Screenshot (416)
@myhacktech still book now button is overlapping.

**Comment by astha2412** [comment]
@myhacktech fill description properly again!

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
The website is fully responsive you just need to align some items properly. Also add this project in style_links.json.

image

image

**Comment by myhacktech** [comment]
> @myhacktech

sure, i will do that

**Pull request closed without merging**
