### PR TITLE
Added Google forms Website Clone

### PR DESCRIPTION
**Pull request by SupriyaGembali**
This PR fixes the issue Google Forms Website Clone #707.
Kindly make a further move sir/mam.

### CODE REVIEW

**Review by VidhiBhatt01 — COMMENTED** [review]
image


Did you make it on your own?? IDTS 👀

**Comment by VidhiBhatt01** [comment]
https://deploy-preview-708--cool-front-end-templates.netlify.app/google%20forms%20clone/google%20forms

**Comment by SupriyaGembali** [comment]
@VidhiBhatt01  I made it my own , additionally I planned to implement cookies in the project , which I guess made mess when deployed. I will rectify the issue . The project runs without any error in my local environment.

**Comment by DEEPIKA-SUK** [comment]
@SupriyaGembali add screenshots

**Comment by SupriyaGembali** [comment]
image

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Add it in style_links.json

**Comment by SupriyaGembali** [comment]
@VidhiBhatt01 I have updated the style_links.json file.

**Comment by DEEPIKA-SUK** [comment]
> image
> 
getting this page only I am not able to see the website. @SupriyaGembali

**Comment by DEEPIKA-SUK** [comment]
@VidhiBhatt01

**Comment by DEEPIKA-SUK** [comment]
@arpit456jain kindly review this PR.

**Comment by arpit456jain** [comment]
@SupriyaGembali 
image

**Comment by arpit456jain** [comment]
#785

**Pull request merged**
