### PR TITLE
added designing

### PR DESCRIPTION
**Pull request by Shobhit61730**
I have changed designing part of footer-top section.
close#373 issue.

### CODE REVIEW

**Comment by Shobhit61730** [comment]
Please merge my PR if it is looks better than previous.

**Review by VidhiBhatt01 — COMMENTED** [review]
Include before-after images in PR description

**Comment by Shobhit61730** [comment]
1. Before image:-
image
2. After image:-
image

**Comment by Shobhit61730** [comment]
Please merge my PR  ,if it looks better.

**Comment by arpit456jain** [comment]
#373

**Comment by arpit456jain** [comment]
@Shobhit61730 actually its not looking good to me plus i don't want changes in footer for if u can find the bug because of which icons are not displaying please create a issue for that
sorry for the inconvenience

**Pull request closed without merging**
