### PR TITLE
add starbucks website

### PR DESCRIPTION
**Pull request by piyushsonawane07**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #483

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
preview

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Link the issue and fill the PR template properly

**Comment by piyushsonawane07** [comment]
Issue Linked

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Make it responsive for all screen sizes.

image

**Comment by arpit456jain** [comment]
@piyushsonawane07

**Comment by VidhiBhatt01** [comment]
Reopen this PR when ready.

**Pull request closed without merging**
