### PR TITLE
Added Letter Animation Project to the file

### PR DESCRIPTION
**Pull request by TANYA-CHAN**
# Description

An interactive letter animation layout using HTML, CSS & JS.

Fixes:  #787 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
https://tanya-chan.github.io/letter-animation/

### CODE REVIEW

**Comment by anamansari062** [comment]
@TANYA-CHAN You have already made a pr in https://github.com/surajm-333/Ace-The-FrontEnd/pull/484

**Comment by TANYA-CHAN** [comment]
It is a front end project too uses CSS for animation so it is a worthy project for this repo also, please consider.

**Review by DEEPIKA-SUK — CHANGES_REQUESTED** [review]
add this project in style_links.json file.

**Review by DEEPIKA-SUK — CHANGES_REQUESTED** [review]
@TANYA-CHAN  Make it responsive for all sizes.

**Comment by TANYA-CHAN** [comment]
@DEEPIKA-SUK what does responsive for all sizes mean? could you please elaborate? I thought this was just a template repo, and my website is dynamic too not only a template. @DEEPIKA-SUK

**Pull request closed without merging**
