### PR TITLE
Added responsive Landing page with dark and light theme also with hamburger menu

### PR DESCRIPTION
**Pull request by AmolShelke2**
# Description

Hey, Project admin as I created the issue in your repository and you assign me to work on it so it is completed and I've creating the Pull request to add my responsive landing page in your cool front end templates repository I hope that you will go through my pr and merge it....
thank you...

Fixes ISSUE [#254](https://github.com/arpit456jain/Cool-Front-End-Templates/issues/254)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Explain the Testing instructions

**Test Configuration**:

- Operating system: windows 
- Version: 11
- Text-editors used: VS code 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
[Landing page](https://responsive-web-design-nu.vercel.app/)

responsive-web-design-nu vercel app_ (1)

### CODE REVIEW

**Review by VidhiBhatt01 — COMMENTED** [review]
Link the issue properly in PR description

**Comment by AmolShelke2** [comment]
> Link the issue properly in PR description

yes..

**Comment by AmolShelke2** [comment]
> > Link the issue properly in PR description
> 
> yes..

linked the issue properly

**Comment by VidhiBhatt01** [comment]
The website is very smooth. Good job 👍

**Comment by AmolShelke2** [comment]
> 

Thanks :D

**Comment by arpit456jain** [comment]
@AmolShelke2 r ru sure u make thi from ur own?

**Comment by AmolShelke2** [comment]
I watched tutorial to create this when I was learning html and css.

**Pull request merged**
