### PR TITLE
New Tech page UI

### PR DESCRIPTION
**Pull request by Abh1shekSingh**
# Description

Following Are the Changes Made:
1. Color Scheme Changes
2. Introduced New Navbar with hamburger animation 
3. Images of High Quality is used, basically I replaced low quality images with high quality
4. Everything is Responsive
5. New Logo Introduced
6. Font Family Changes

Fixes:  #681 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by Abh1shekSingh** [comment]
Please Review This PR

**Comment by Abh1shekSingh** [comment]
@VidhiBhatt01 @arpit456jain Please Review This PR

**Comment by arpit456jain** [comment]
@Abh1shekSingh u r changing 727 files 
ur PR contains lots of unnecessary files

**Comment by Abh1shekSingh** [comment]
How this could be possible bro

**Comment by Abh1shekSingh** [comment]
@arpit456jain Mereko pata nhi yeh show ho raha hai ki, your banch in 9 commits ahead. on every branch i created in fork repo

**Comment by arpit456jain** [comment]
Delete it
Fork it again
Make a new PR 
Close this one

**Comment by Abh1shekSingh** [comment]
ok

**Pull request closed without merging**
