### PR TITLE
Added microsoft clone of teams files

### PR DESCRIPTION
**Pull request by XZANATOL**
# Description

Added a clone of one of the microsoft teams page (the page where the groups are listed)

Fixes:  #475 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

https://htmlpreview.github.io/?https://github.com/XZANATOL/Cool-Front-End-Templates/blob/Teams_Clone/Microsoft_Teams_Clone/index.html

### CODE REVIEW

**Comment by DEEPIKA-SUK** [comment]
@XZANATOL 
Screenshot (100)
Correct this. Not able to scroll down in this case.

**Comment by XZANATOL** [comment]
@DEEPIKA-SUK Done. Should be scrollable now.

**Review by DEEPIKA-SUK — APPROVED** [review]

**Comment by arpit456jain** [comment]
@astha2412 @VidhiBhatt01 is it responsive in ur system ?

**Review by VidhiBhatt01 — COMMENTED** [review]
The website is responsive but I think the boxes must be as shown in the right side of below image.

image

**Comment by XZANATOL** [comment]
Ah I forgot to fix that before first submitting. Should be good now.

**Review by VidhiBhatt01 — COMMENTED** [review]
Still the same, it must be like one box per row.

image

**Comment by XZANATOL** [comment]
Ah ok gimme a min

**Comment by XZANATOL** [comment]
Done.

**Review by VidhiBhatt01 — APPROVED** [review]
Perfect!

**Pull request merged**
