### PR TITLE
Made the site responsive

### PR DESCRIPTION
**Pull request by Sakshi-1701**
Made some changes in the code and added media queries so as to make the clone site responsive.
Also added a hamburger navbar (for small sized devices)

Fixes:  #470

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
issue470_1

### CODE REVIEW

**Review by astha2412 — COMMENTED** [review]
https://deploy-preview-493--cool-front-end-templates.netlify.app/apple%20webiste%20ui%20clone/

**Comment by astha2412** [comment]
@Sakshi-1701 Good Work! you just only need to fill in all the information properly, [x ] remove one space before or after x.

**Comment by Sakshi-1701** [comment]
> @Sakshi-1701 Good Work! you just only need to fill in all the information properly, [x ] remove one space before or after x.

Thank you😊 I've done the correction.

**Comment by Sakshi-1701** [comment]
@astha2412 Please review this and let me know if any other correction has to be done.

**Review by VidhiBhatt01 — COMMENTED** [review]
approved

**Pull request merged**
