### PR TITLE
I add new cool template vegetable website

### PR DESCRIPTION
**Pull request by adi2002vicky**
Screenshot 2022-03-04 100156
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue no.)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Explain the Testing instructions

**Test Configuration**:

- Operating system:window
- Version:10
- Text-editors used:vs code

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by arpit456jain** [comment]
@adi2002vicky there are lots of file in this PR which is not related to this template please remove them all

**Comment by adi2002vicky** [comment]
hii i am gssoc22 contributor pls assign me sir and merge my pr @arpit456jain

**Comment by adi2002vicky** [comment]
> @adi2002vicky there are lots of file in this PR which is not related to this template please remove them all

okk sir sorry

**Comment by adi2002vicky** [comment]
@arpit456jain sir i am not know how to dlt extra file because my previous pr [i add new cool front end template for money loaning website] you added so both file show what can i do ........
this new pr is show in down

**Comment by arpit456jain** [comment]
@astha2412 @VidhiBhatt01 please help him
@adi2002vicky u can also take help from other contributors ask them how to do it

**Comment by VidhiBhatt01** [comment]
@adi2002vicky ping me on discord

**Comment by VidhiBhatt01** [comment]
no

**Comment by adi2002vicky** [comment]
css html file are deleted mam

**Comment by VidhiBhatt01** [comment]
Okay, I will try removing other files. Till then can you try by creating a new PR??

**Comment by adi2002vicky** [comment]
Okk mam

**Comment by adi2002vicky** [comment]
after creating new pull request come same problem

**Comment by adi2002vicky** [comment]
all files are show in changing file section

**Comment by arpit456jain** [comment]
make a new PR

**Pull request closed without merging**
