### PR TITLE
Added Huddle Landing Page

### PR DESCRIPTION
**Pull request by Abh1shekSingh**
# Description

Huddle Landing Page Added. It is just a concept based landing page from which anyone can take his inspiration

Fixes:  #722 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
huddle

### CODE REVIEW

**Comment by Abh1shekSingh** [comment]
@arpit456jain Please Review this Landing Page PR

**Comment by DEEPIKA-SUK** [comment]
@Abh1shekSingh fix this
Screenshot (122)

**Comment by Abh1shekSingh** [comment]
@DEEPIKA-SUK  please please, don't see responsiveness using console log

**Comment by Abh1shekSingh** [comment]
Bro console always give error in responsiveness. Always check by moving the actual browser

**Review by DEEPIKA-SUK — APPROVED** [review]

**Pull request merged**
