### PR TITLE
Added Festivals In India

### PR DESCRIPTION
**Pull request by AyushJ16**
# Description

Added Festivals of India website Template

Fixes:  #803 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Checklist:

- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# https://ayushj16.github.io/Festivals-In-India/
Screenshot (46)

### CODE REVIEW

**Review by DEEPIKA-SUK — CHANGES_REQUESTED** [review]
@AyushJ16 resolve the merge conflicts and update the correct link in style_links.json file.

**Comment by AyushJ16** [comment]
@DEEPIKA-SUK I have resolved the conflicts.

**Comment by DEEPIKA-SUK** [comment]
> @AyushJ16 resolve the merge conflicts and update the correct link in style_links.json file.

.

**Comment by AyushJ16** [comment]
@DEEPIKA-SUK see if there's any other change required .

**Review by DEEPIKA-SUK — APPROVED** [review]

**Comment by arpit456jain** [comment]
@AyushJ16 merge conflicts

**Comment by AyushJ16** [comment]
@arpit456jain see if there's any other change required.

**Pull request merged**
