### PR TITLE
Payment-Page Template with HTML, CSS and JS

### LINKED ISSUE #327: Add Payment-Page with HTML, CSS and JS
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [x] Documentaion

## **Description**

- A payment page using frontend.

## **Stacks Used**

- HTML
- CSS
- Javascript

I am a GSSOC'22 Contributor. Please assign this issue to me.

### PR DESCRIPTION
**Pull request by darkhorse-2000**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #327

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Explain the Testing instructions

**Test Configuration**:

- Operating system: Windows
- Version: 11
- Text-editors used: VS Code

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot (5)

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
@darkhorse-2000 please make the size of the box bigger so that it properly fits the screen.

image

**Comment by arpit456jain** [comment]
@darkhorse-2000 make its responsive within 2 days

**Review by astha2412 — CHANGES_REQUESTED** [review]
Take 2-3 days more and make it more responsive.

**Comment by arpit456jain** [comment]
@darkhorse-2000 make a new PR when its ready

**Pull request closed without merging**
