### PR TITLE
added New Interface of Pizza corner project

### PR DESCRIPTION
**Pull request by Abh1shekSingh**
# Description

Added New Pizza Corner Project New Interface (Separately)

Fixes:  #833 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

pizza4
pizza3
pizza2
pizza1

### CODE REVIEW

**Comment by Abh1shekSingh** [comment]
@VidhiBhatt01 @arpit456jain Added the template separately and also updated styles.json

**Review by VidhiBhatt01 — COMMENTED** [review]
https://deploy-preview-882--cool-front-end-templates.netlify.app/pizzacorner_newinterface/

**Review by DEEPIKA-SUK — CHANGES_REQUESTED** [review]
@Abh1shekSingh make it responsive and links in the navbar(menu,services) are not working, resolve merge conflicts also.

**Comment by VidhiBhatt01** [comment]
This is pending since a long time, @arpit456jain please merge this. Just give one level less than the usual one as it is not fully responsive

**Pull request merged**
