### PR TITLE
Found covid19/index.html page is not responsive and attractive UI template too. #234 

### PR DESCRIPTION
**Pull request by ragineeguptta**
# Description
Made Covid-19 page  responsive

Fixes # (issue no.)

1. Adding open popup model in How to prevent button
2. clickable link
3. responsive desgine

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Explain the Testing instructions

**Test Configuration**:

- Operating system:
- Version:
- Text-editors used:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Link the issue in PR description

**Comment by VidhiBhatt01** [comment]
@ragineeguptta

**Comment by arpit456jain** [comment]
@ragineeguptta i am closing PR because u r not solving merge conflicts

**Comment by arpit456jain** [comment]
make a new PR

**Pull request closed without merging**
