### PR TITLE
full css house game

### PR DESCRIPTION
**Pull request by iamrahulmahato**
# Description

A fully animated house game made by CSS and HTML with changing background and with two-mode

Fixes:  #499 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Web capture_2-4-2022_133540_127 0 0 1
Web capture_2-4-2022_133244_127 0 0 1
Web capture_2-4-2022_133219_127 0 0 1
160241975-ae024c01-ea47-4d55-8074-7d47f1eb6a84

### CODE REVIEW

**Comment by arpit456jain** [comment]
@iamrahulmahato 
did u make it from ur own
did u add this in any other project

**Comment by iamrobin123** [comment]
@arpit456jain 
Made by me but also taken help from youtube and blog
No I haven't add this project in any other project

**Comment by iamrahulmahato** [comment]
@arpit456jain
Made by me but also taken help from youtube and blog
No I haven't add this project in any other project

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
image

Make it responsive for all screen sizes.
Mention the references in PR description.
Add this project in style_links.json

**Comment by iamrahulmahato** [comment]
In most of the standard size it is responsive
Screenshot 2022-04-04 050144
Screenshot 2022-04-04 050107
Screenshot 2022-04-04 050029

**Comment by arpit456jain** [comment]
@iamrahulmahato 
https://www.youtube.com/watch?v=wUBmZCwl61U
95% code is same we can't accept this PR

**Pull request closed without merging**
