### PR TITLE
Revamped the Engineers Copied frontend template

### PR DESCRIPTION
**Pull request by IshitaGarg-01**
Inserted the logo of website , added information in form of cards , modified the form page , created a footer, revamped the About Us page , added line below texts .

Fixes:  #442 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

[Images.before.after.zip](https://github.com/arpit456jain/Cool-Front-End-Templates/files/8339219/Images.before.after.zip)
Here are the images before n after.

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Increase the fonts, I can barely see anything.

image


Also, I think there are some extra files in this PR. Kindly remove them.

https://deploy-preview-529--cool-front-end-templates.netlify.app/engineers%20copied%20web/index.html

**Comment by IshitaGarg-01** [comment]
> Increase the fonts, I can barely see anything.
> 
> image
> 
> Also, I think there are some extra files in this PR. Kindly remove them.
> 
> https://deploy-preview-529--cool-front-end-templates.netlify.app/engineers%20copied%20web/index.html

@VidhiBhatt01 ma'am I haven't made this file responsive so that's why you aren't able to see the font after decreasing screen size  and I would also like to ask that is it possible for you to manually remove the extra files?

**Review by VidhiBhatt01 — COMMENTED** [review]
Okay, I will remove the files. 

You have made it responsive, you just need to increase the font size in media elements.

**Comment by IshitaGarg-01** [comment]
> Okay, I will remove the files.
> 
> You have made it responsive, you just need to increase the font size in media elements.

Ok ma'am I will increase the font size !

**Comment by IshitaGarg-01** [comment]
> Increase the fonts, I can barely see anything.
> 
> image
> 
> Also, I think there are some extra files in this PR. Kindly remove them.
> 
> https://deploy-preview-529--cool-front-end-templates.netlify.app/engineers%20copied%20web/index.html

@VidhiBhatt01 ma'am I have increased the font-size . Can you please review it once ?

**Review by VidhiBhatt01 — APPROVED** [review]
LGTM. @astha2412 @DEEPALI-SUK @DEEPIKA-SUK can anyone of you please verify?

**Review by DEEPIKA-SUK — APPROVED** [review]

**Pull request merged**
