### PR TITLE
recipe website

### PR DESCRIPTION
**Pull request by DragonUncaged**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #758 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [ ] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTAC

### CODE REVIEW

**Comment by DEEPIKA-SUK** [comment]
https://deploy-preview-783--cool-front-end-templates.netlify.app/recipe%20website/

**Comment by DEEPIKA-SUK** [comment]
@DragonUncaged 
1. Reduce image size to make it user friendly.
2. Give some space after text in right side.
Screenshot 2022-05-09 182129

**Comment by DEEPIKA-SUK** [comment]
@DragonUncaged add project in style_links.json file.

**Comment by DragonUncaged** [comment]
> @DragonUncaged add project in style_links.json file.

Done !!

image

**Comment by DEEPIKA-SUK** [comment]
@DragonUncaged add project in style_links.json file.

**Comment by DragonUncaged** [comment]
> @DragonUncaged add project in style_links.json file.

Done!!

**Review by DEEPIKA-SUK — CHANGES_REQUESTED** [review]
@DragonUncaged For the full size screen also reduce the image size as well as font size to make it user friendly.

**Comment by DragonUncaged** [comment]
https://github.com/arpit456jain/Amazing-Css-Effects/pull/652
https://github.com/arpit456jain/Amazing-Js-Projects/pull/646

**Review by DEEPIKA-SUK — CHANGES_REQUESTED** [review]
@DragonUncaged resolve the merge conflicts and do the suggested changes as soon as possilble.

**Comment by DragonUncaged** [comment]
> @DragonUncaged resolve the merge conflicts and do the suggested changes as soon as possilble.

done!!

**Comment by DragonUncaged** [comment]
> That is just the design. It looks Better. it is a simple website that doesn't have anything so bigger makes it look better

are you talking about the desktop view

**Review by DEEPIKA-SUK — CHANGES_REQUESTED** [review]
@DragonUncaged Resolve the merge conflicts.

**Review by VidhiBhatt01 — APPROVED** [review]

**Comment by arpit456jain** [comment]
@DragonUncaged  its not website its just 2 photos

**Pull request merged**
