### PR TITLE
Feat- added banana taranslator template

### PR DESCRIPTION
**Pull request by Mohasin-Haque**
# Description

I have added Translator template . 

Fixes:  #842)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
image

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
This is so cool man, did you make it on your own!?

image
Just make it responsive for all screen sizes and apply some CSS so that the text where the arrow is pointing is properly visible.

**Comment by VidhiBhatt01** [comment]
https://deploy-preview-854--cool-front-end-templates.netlify.app/translator%20template/

**Comment by Mohasin-Haque** [comment]
Fixed the text overflow 

image
@VidhiBhatt01

**Review by DEEPIKA-SUK — CHANGES_REQUESTED** [review]
@Mohasin-Haque make it responsive.
Screenshot 2022-05-21 100348

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Apply CSS on "Output will come here"

**Comment by DEEPIKA-SUK** [comment]
@Mohasin-Haque add other translators also and do it asap.

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Resolve merge conflicts too

**Review by VidhiBhatt01 — COMMENTED** [review]
@Mohasin-Haque

**Comment by Mohasin-Haque** [comment]
> @Mohasin-Haque

@VidhiBhatt01 so sorry. I am not well and also not so much active. So I will do it asap as my health becomes some good. I hope you understand.

**Pull request merged**
