### PR TITLE
Template for Notes providing Website

### PR DESCRIPTION
**Pull request by priyanshi1282**
# Description
MedEasy is a MBBS Notes providing Website Template. This will give you a basic website for Notes Providing Services.

Fixes:  #535 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot (85)
Screenshot (86)
Screenshot (87)
responsive1
responsive2

### Please consider this under GSSoC'22 contribution.

### CODE REVIEW

**Review by VidhiBhatt01 — COMMENTED** [review]
https://deploy-preview-545--cool-front-end-templates.netlify.app/medeasy website

This is beautiful, did you make it on your own? 👀

**Comment by priyanshi1282** [comment]
> https://deploy-preview-545--cool-front-end-templates.netlify.app/medeasy website
> 
> This is beautiful, did you make it on your own? 👀

Thanks @VidhiBhatt01😀. Beside development, I have interest in designing too. So I made it by my own along with the logo designing.

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Cool, I hope what you say is true!

Just resolve the merge conflicts and we are good to go : )

**Comment by priyanshi1282** [comment]
@VidhiBhatt01 thanks for trusting 😀.
 Also I resolved the conflicts.

**Comment by VidhiBhatt01** [comment]
Awesome!

**Comment by arpit456jain** [comment]
@priyanshi1282 i am merging this PR 

but we need other pages as well so if u r interested u can do it
@VidhiBhatt01 ek issue create kr dena

**Comment by priyanshi1282** [comment]
> @priyanshi1282 i am merging this PR
> 
> but we need other pages as well so if u r interested u can do it @VidhiBhatt01 ek issue create kr dena

actually my internals are going on, so I will be needing a week or more to add few more pages.

**Comment by VidhiBhatt01** [comment]
@priyanshi1282 yeah yeah at your ease. Jab bhi karna ho tab raise the issue yourself and tag me. I will assign

**Pull request merged**
