### PR TITLE
Making the admin panel fully responsive

### PR DESCRIPTION
**Pull request by soumali28**
# Description

Made the admin panel fully responsive.
Fixes:  #566 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

Gyan Uday - Google Chrome 06-04-2022 12_47_37
Gyan Uday - Google Chrome 06-04-2022 12_47_28

Gyan Uday - Google Chrome 06-04-2022 12_47_37

https://user-images.githubusercontent.com/66300439/161922738-75ebd91b-5b5f-4b27-a85c-81493057c5d9.mp4

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
1. Still not fixed.

image

2. Remove Food template files from this PR.

**Comment by VidhiBhatt01** [comment]
https://deploy-preview-590--cool-front-end-templates.netlify.app/admin%20dashboard/

**Comment by VidhiBhatt01** [comment]
It looks fine in the video she attached, is it just me who is facing the issue? @DEEPALI-SUK please verify

**Comment by soumali28** [comment]
U are viewing  it in the tablet version I made it mobile responsive.

**Comment by VidhiBhatt01** [comment]
It must be responsive for all screen sizes

**Comment by soumali28** [comment]
> It must be responsive for all screen sizes

Ok then i'll do it for the tablet and make a new pr.

**Comment by VidhiBhatt01** [comment]
No need to make a new PR. Add commits in this one only

**Comment by soumali28** [comment]
> No need to make a new PR. Add commits in this one only

Ok

**Comment by soumali28** [comment]
I have made the commits and made it responsive for the tablet also.
Gyan Uday - Google Chrome 06-04-2022 18_01_30

**Comment by VidhiBhatt01** [comment]
It's not working on my device. Any of the other mentors please help me review this.

**Comment by soumali28** [comment]
@arpit456jain I think the level could be increased by 1 as it took me 3days to make this website responsive as the code was really bad.

**Comment by soumali28** [comment]
Yup thanks @astha2412

**Pull request merged**
