### PR TITLE
Made the E-Commerce shopping website fully responsive

### PR DESCRIPTION
**Pull request by Sakshi-1701**
# Description

1. Made the site fully responsive.
2. Fixed the Navbar
3. Removed extra spaces and overflowing texts

Fixes:  #642

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
pic1
pic2

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Still not responsive. Plus there are 2 hamburger buttons. Fix it.
image

**Comment by VidhiBhatt01** [comment]
https://deploy-preview-656--cool-front-end-templates.netlify.app/e%20commerce%20shopping%20website%20template/

**Comment by Sakshi-1701** [comment]
@VidhiBhatt01 Umm...Its working pretty fine in my local machine i.e its responsive, also I have already fixed that 2 menu icon issue.
I've attached the screenshots above

**Comment by arpit456jain** [comment]
@Sakshi-1701 in small screen the images are very large and its not responsive check again

**Comment by Sakshi-1701** [comment]
It is working fine in my VSC. 
I guess this happened after I solved the conflicts with the branch where I deleted wrong part of the code.
So what shall I do now?
Here are the screenshots that the images are responsive in mobile view
ecom1
ecom2

**Review by VidhiBhatt01 — COMMENTED** [review]
I am still facing the same problem @Sakshi-1701. Take help from someone on the discord server and fix it

**Comment by yash-25log** [comment]
> @VidhiBhatt01 Umm...Its working pretty fine in my local machine i.e its responsive, also I have already fixed that 2 menu icon issue.
> I've attached the screenshots above

Um this is because u need to change dimensions to test it 
On my device too it isn't responsive
Maybe try changing dimensions to a phone rather than tablet
U too will see the issue

**Comment by yash-25log** [comment]
> > @VidhiBhatt01 Umm...Its working pretty fine in my local machine i.e its responsive, also I have already fixed that 2 menu icon issue.
> > I've attached the screenshots above
> 
> Um this is because u need to change dimensions to test it 
> On my device too it isn't responsive
> Maybe try changing dimensions to a phone rather than tablet
> U too will see the issue

**Pull request closed without merging**
