### PR TITLE
Local Fast Food added

### PR DESCRIPTION
**Pull request by shahnehal0407**
# Description

Added a new template.
This template was created for local fast food shop. It consist of food gallery and also costumer can read review and all add their review.

## Type of change
Added a new template.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### CODE REVIEW

**Comment by DEEPIKA-SUK** [comment]
https://deploy-preview-825--cool-front-end-templates.netlify.app/local%20fast%20food/

**Review by DEEPIKA-SUK — CHANGES_REQUESTED** [review]
@shahnehal0407 Make it responsive, toggle button is not working, resolve merge conflicts.

**Review by DEEPIKA-SUK — COMMENTED** [review]
@shahnehal0407 list the resources from where you have taken help.

**Review by VidhiBhatt01 — COMMENTED** [review]
@DEEPIKA-SUK don't review further if the template itself is incomplete

**Pull request closed without merging**
