### PR TITLE
Travel Website - Travellrr.

### PR DESCRIPTION
**Pull request by kunal-kataria**
# Description
I have added a new template of Travel Website template. This website is made using HTML, CSS and JavaScript. I have also used Font Awesome for social media icons. I have used pictures from Unspash and Pexels. 

Fixes:  #
# Types of Change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] I have made this website on my own.
- [x] I took help from online resources like Unspalsh, Pexels, developer.mozilla.org, etc.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no conflicts.

Screenshot of the Website:
preview
preview 2
preview 3

### CODE REVIEW

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
Link the issue in description

**Review by kunal-kataria — COMMENTED** [review]
I have removed main.json as it was an empty file. I have also changed the title of the template in style_links.json

**Comment by kunal-kataria** [comment]
If there are any other changes to be made, then please specify the problem.

**Comment by DEEPIKA-SUK** [comment]
https://deploy-preview-819--cool-front-end-templates.netlify.app/travel%20website/

**Review by VidhiBhatt01 — CHANGES_REQUESTED** [review]
image
Fix this too. Btw the UI is awesome!! Did you make this on your own?

**Comment by DEEPIKA-SUK** [comment]
@kunal-kataria add the issue number in description.

**Review by VidhiBhatt01 — COMMENTED** [review]
@kunal-kataria

**Review by VidhiBhatt01 — COMMENTED** [review]
Reopen this when ready

**Pull request closed without merging**
